/** Short plain-language descriptions for Profile Skills picker hover/focus. */

const PROFILE_SKILL_DESCRIPTIONS: Record<string, string> = {
  "3D modeling": "Creating or refining visual, product, or media work in this specialty.",
  "Account management": "Attracting, informing, or converting customers through this commercial specialty.",
  "Accountability": "Taking ownership of commitments, outcomes, and mistakes without shifting blame.",
  "Accounting": "Recording, classifying, and reporting financial transactions and results.",
  "Accounts payable": "Managing money owed to suppliers and paying invoices accurately and on time.",
  "Accounts receivable": "Tracking money owed by customers and collecting payments reliably.",
  "Active listening": "Giving full attention, reflecting understanding, and responding thoughtfully to others.",
  "Adaptability": "Adjusting approach and priorities when conditions, tools, or expectations change.",
  "Adult education": "Designing or delivering learning experiences in this education specialty.",
  "Advocacy": "Speaking up for people, causes, or needs so they are heard and acted on.",
  "Agile facilitation": "Planning and coordinating work so teams deliver valued outcomes on time.",
  "Agricultural machinery operation": "Applying practical knowledge in this agricultural or environmental specialty.",
  "Agroecology": "Applying practical knowledge in this agricultural or environmental specialty.",
  "Air traffic coordination": "Supporting safe aviation operations in this specialty.",
  "Aircraft maintenance": "Supporting safe aviation operations in this specialty.",
  "Ambulance driving": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Animation": "Creating or refining visual, product, or media work in this specialty.",
  "API design": "Using this technology or practice to build, run, or secure digital systems.",
  "Arabic": "Communicating effectively in this language or language service specialty.",
  "Archiving": "Organizing and preserving records so they can be found and trusted later.",
  "Armenian": "Communicating effectively in this language or language service specialty.",
  "Assessment design": "Designing tests and evaluations that fairly measure learning or performance.",
  "Attention to detail": "Noticing small errors and finishing work carefully and accurately.",
  "Audio engineering": "Creating or refining visual, product, or media work in this specialty.",
  "Auditing": "Examining records and processes to verify accuracy, compliance, and control.",
  "AWS": "Using this technology or practice to build, run, or secure digital systems.",
  "Azure": "Using this technology or practice to build, run, or secure digital systems.",
  "Baking": "Preparing food or running hospitality operations to quality and safety standards.",
  "Bartending": "Preparing food or running hospitality operations to quality and safety standards.",
  "Beekeeping": "Applying practical knowledge in this agricultural or environmental specialty.",
  "Blueprint reading": "Creating or refining visual, product, or media work in this specialty.",
  "Boat operation": "Operating or working safely in this maritime or watercraft specialty.",
  "Bookkeeping": "Keeping day-to-day financial records organized and up to date.",
  "Boundary setting": "Defining and maintaining healthy limits on time, roles, and responsibilities.",
  "Brand design": "Creating or refining visual, product, or media work in this specialty.",
  "Bricklaying": "Performing this construction or building trade to accepted safety and quality standards.",
  "Budgeting": "Planning and tracking income and spending against goals and limits.",
  "Bus driving": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Business analysis": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "C": "Using this technology or practice to build, run, or secure digital systems.",
  "C++": "Using this technology or practice to build, run, or secure digital systems.",
  "CAD drafting": "Creating or refining visual, product, or media work in this specialty.",
  "Care coordination": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Carpentry": "Performing this construction or building trade to accepted safety and quality standards.",
  "Case documentation": "Supporting people or civic processes through this service specialty.",
  "Case management": "Applying rules, research, or formal process in this legal or policy specialty.",
  "Catering": "Preparing food or running hospitality operations to quality and safety standards.",
  "Change management": "Planning and coordinating work so teams deliver valued outcomes on time.",
  "Chinese (Mandarin)": "Communicating effectively in this language or language service specialty.",
  "Choreography": "Practicing this performance, coaching, or creative production specialty.",
  "Civic engagement": "Participating in community, public, or governance activities that serve the common good.",
  "Clinical documentation": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Cloud architecture": "Using this technology or practice to build, run, or secure digital systems.",
  "CNC machining": "Applying engineering or manufacturing methods in this technical specialty.",
  "Coaching (sports)": "Practicing this performance, coaching, or creative production specialty.",
  "Collaboration": "Working effectively with others toward shared goals and shared responsibility.",
  "Commercial fishing": "Operating or working safely in this maritime or watercraft specialty.",
  "Communication": "Expressing ideas clearly and understanding others across spoken and written channels.",
  "Community organizing": "Bringing people together to identify needs and take collective action.",
  "Compassion": "Responding to others’ hardship with care and a willingness to help.",
  "Compliance": "Applying rules, research, or formal process in this legal or policy specialty.",
  "Concrete work": "Performing this construction or building trade to accepted safety and quality standards.",
  "Conflict de-escalation": "Reducing tension in heated situations so dialogue can continue safely.",
  "Conflict resolution": "Helping people work through disagreements toward a fair and durable outcome.",
  "Consensus building": "Guiding a group toward broad agreement while respecting different views.",
  "Constitutional literacy": "Applying rules, research, or formal process in this legal or policy specialty.",
  "Construction estimating": "Performing this construction or building trade to accepted safety and quality standards.",
  "Construction supervision": "Performing this construction or building trade to accepted safety and quality standards.",
  "Contract management": "Creating, tracking, and administering agreements through their lifecycle.",
  "Cooking": "Preparing food or running hospitality operations to quality and safety standards.",
  "Copyediting": "Crafting or refining text so it is clear, accurate, and fit for purpose.",
  "Copywriting": "Crafting or refining text so it is clear, accurate, and fit for purpose.",
  "Cost accounting": "Measuring and analyzing the cost of products, services, or activities.",
  "Counseling techniques": "Supporting people or civic processes through this service specialty.",
  "CPR": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Creativity": "Generating useful new ideas, approaches, or solutions to problems.",
  "Crisis hotline support": "Supporting people or civic processes through this service specialty.",
  "Crisis response": "Preventing harm and responding effectively in safety or emergency situations.",
  "Critical thinking": "Examining evidence and assumptions before drawing conclusions or acting.",
  "Crop management": "Applying practical knowledge in this agricultural or environmental specialty.",
  "Cross-cultural communication": "Communicating respectfully and clearly across cultural and linguistic differences.",
  "Curiosity": "Asking good questions and seeking to understand before judging.",
  "Curriculum design": "Creating or refining visual, product, or media work in this specialty.",
  "Customer service": "Helping people resolve needs courteously, promptly, and professionally.",
  "Customer service systems": "Using tools and processes that support reliable customer support.",
  "Cybersecurity": "Using this technology or practice to build, run, or secure digital systems.",
  "Data analysis": "Gathering and interpreting evidence using methods from this research specialty.",
  "Data visualization": "Gathering and interpreting evidence using methods from this research specialty.",
  "Database administration": "Using this technology or practice to build, run, or secure digital systems.",
  "Decision making": "Choosing a course of action using available information and clear criteria.",
  "Defensive driving": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Dental assisting": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Design thinking": "Creating or refining visual, product, or media work in this specialty.",
  "DevOps": "Using this technology or practice to build, run, or secure digital systems.",
  "Digital marketing": "Using this technology or practice to build, run, or secure digital systems.",
  "Diplomacy": "Handling sensitive topics tactfully while protecting relationships and goals.",
  "Docker": "Using this technology or practice to build, run, or secure digital systems.",
  "Driving (car / light vehicle)": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Driving instruction": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Drywall installation": "Performing this construction or building trade to accepted safety and quality standards.",
  "Early childhood education": "Designing or delivering learning experiences in this education specialty.",
  "Econometrics": "Gathering and interpreting evidence using methods from this research specialty.",
  "Election administration": "Supporting people or civic processes through this service specialty.",
  "Electrical engineering": "Working with electrical systems, installation, or diagnosis under safety standards.",
  "Electrical installation": "Working with electrical systems, installation, or diagnosis under safety standards.",
  "Electrical troubleshooting": "Working with electrical systems, installation, or diagnosis under safety standards.",
  "Electronics repair": "Applying engineering or manufacturing methods in this technical specialty.",
  "Email marketing": "Attracting, informing, or converting customers through this commercial specialty.",
  "Emergency medical technician (EMT)": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Emergency preparedness": "Preventing harm and responding effectively in safety or emergency situations.",
  "Emotional intelligence": "Recognizing emotions in yourself and others and using that awareness wisely.",
  "Empathy": "Understanding another person’s feelings and perspective from their point of view.",
  "English": "Communicating effectively in this language or language service specialty.",
  "Environmental assessment": "Applying practical knowledge in this agricultural or environmental specialty.",
  "Ethical judgment": "Choosing actions that align with fairness, honesty, and shared principles.",
  "Ethnographic research": "Gathering and interpreting evidence using methods from this research specialty.",
  "Experiment design": "Creating or refining visual, product, or media work in this specialty.",
  "Facilitation": "Guiding meetings or discussions so everyone can contribute and reach outcomes.",
  "Feedback giving": "Offering clear, constructive observations that help others improve.",
  "Feedback receiving": "Listening to critique without defensiveness and using it to improve.",
  "Financial analysis": "Interpreting financial data to support decisions and assess performance.",
  "Financial modeling": "Building structured forecasts and scenarios from financial assumptions.",
  "Fire safety": "Preventing harm and responding effectively in safety or emergency situations.",
  "First aid": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Fitness instruction": "Practicing this performance, coaching, or creative production specialty.",
  "Flexibility": "Staying effective when plans, roles, or schedules need to change.",
  "Flight instruction": "Supporting safe aviation operations in this specialty.",
  "Flooring installation": "Performing this construction or building trade to accepted safety and quality standards.",
  "Food safety (HACCP)": "Preparing food or running hospitality operations to quality and safety standards.",
  "Forestry": "Applying practical knowledge in this agricultural or environmental specialty.",
  "Forklift operation": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "French": "Communicating effectively in this language or language service specialty.",
  "Fundraising": "Securing financial support from donors, partners, or investors.",
  "German": "Communicating effectively in this language or language service specialty.",
  "GIS mapping": "Gathering and interpreting evidence using methods from this research specialty.",
  "Git": "Using this technology or practice to build, run, or secure digital systems.",
  "Glazing": "Performing this construction or building trade to accepted safety and quality standards.",
  "Google Cloud": "Using this technology or practice to build, run, or secure digital systems.",
  "Grant writing": "Preparing funding proposals that explain need, plan, and expected impact.",
  "Graphic design": "Creating or refining visual, product, or media work in this specialty.",
  "Hazardous materials handling": "Preventing harm and responding effectively in safety or emergency situations.",
  "Health education": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Heavy equipment operation": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Hotel operations": "Preparing food or running hospitality operations to quality and safety standards.",
  "HTML / CSS": "Using this technology or practice to build, run, or secure digital systems.",
  "Humility": "Recognizing limits, valuing others’ contributions, and staying open to learning.",
  "HVAC installation": "Installing or maintaining heating, ventilation, and air-conditioning systems.",
  "HVAC maintenance": "Installing or maintaining heating, ventilation, and air-conditioning systems.",
  "Illustration": "Creating or refining visual, product, or media work in this specialty.",
  "Incident command": "Preventing harm and responding effectively in safety or emergency situations.",
  "Inclusion": "Creating space where people of different backgrounds can participate fully.",
  "Industrial design": "Creating or refining visual, product, or media work in this specialty.",
  "Industrial maintenance": "Applying engineering or manufacturing methods in this technical specialty.",
  "Initiative": "Starting useful action without waiting to be told every step.",
  "Instructional design": "Designing learning experiences, materials, and activities that help people build skills.",
  "Insulation installation": "Performing this construction or building trade to accepted safety and quality standards.",
  "Integrity": "Acting honestly and consistently with stated values, even when inconvenient.",
  "Intercultural competence": "Working effectively with people from different cultural backgrounds.",
  "Interior design": "Creating or refining visual, product, or media work in this specialty.",
  "Interpersonal communication": "Building understanding and rapport in one-to-one and small-group interactions.",
  "Interpretation (consecutive)": "Communicating effectively in this language or language service specialty.",
  "Interpretation (simultaneous)": "Communicating effectively in this language or language service specialty.",
  "Inventory management": "Tracking stock levels, movement, and replenishment to avoid shortages or waste.",
  "Investment analysis": "Evaluating assets or opportunities for risk, return, and fit.",
  "Irrigation systems": "Applying practical knowledge in this agricultural or environmental specialty.",
  "IT support": "Using this technology or practice to build, run, or secure digital systems.",
  "Java": "Using this technology or practice to build, run, or secure digital systems.",
  "JavaScript": "Using this technology or practice to build, run, or secure digital systems.",
  "Kubernetes": "Using this technology or practice to build, run, or secure digital systems.",
  "Laboratory techniques": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Leadership": "Guiding people toward goals while supporting their growth and accountability.",
  "Lean manufacturing": "Applying engineering or manufacturing methods in this technical specialty.",
  "Learning management systems": "Designing or delivering learning experiences in this education specialty.",
  "Legal research": "Gathering and interpreting evidence using methods from this research specialty.",
  "Legislative drafting": "Gathering and interpreting evidence using methods from this research specialty.",
  "Lifeguarding": "Preventing harm and responding effectively in safety or emergency situations.",
  "Linux administration": "Using this technology or practice to build, run, or secure digital systems.",
  "Livestock management": "Applying practical knowledge in this agricultural or environmental specialty.",
  "Machine learning": "Building and applying AI / machine learning models that learn patterns from data.",
  "Marine navigation": "Operating or working safely in this maritime or watercraft specialty.",
  "Market research": "Gathering and interpreting evidence using methods from this research specialty.",
  "Masonry": "Performing this construction or building trade to accepted safety and quality standards.",
  "Mechanical engineering": "Applying engineering or manufacturing methods in this technical specialty.",
  "Mechatronics": "Applying engineering or manufacturing methods in this technical specialty.",
  "Mediation (formal)": "Applying rules, research, or formal process in this legal or policy specialty.",
  "Medical coding": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Medical interpreting": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Mentoring": "Supporting someone’s development through guidance, feedback, and example.",
  "Mobile app development": "Using this technology or practice to build, run, or secure digital systems.",
  "Motion graphics": "Creating or refining visual, product, or media work in this specialty.",
  "Motivation": "Sustaining energy and purpose in yourself and helping others stay engaged.",
  "Motorcycle riding": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Music performance": "Practicing this performance, coaching, or creative production specialty.",
  "Needs assessment": "Supporting people or civic processes through this service specialty.",
  "Negotiation": "Reaching agreements that balance interests through dialogue and trade-offs.",
  "Network administration": "Using this technology or practice to build, run, or secure digital systems.",
  "Node.js": "Using this technology or practice to build, run, or secure digital systems.",
  "Notary services": "Applying rules, research, or formal process in this legal or policy specialty.",
  "Nursing": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Occupational health and safety": "Preventing harm and responding effectively in safety or emergency situations.",
  "Off-road vehicle operation": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Office administration": "Keeping organizational routines, records, and support tasks running smoothly.",
  "Organic farming": "Applying practical knowledge in this agricultural or environmental specialty.",
  "Painting and finishing": "Performing this construction or building trade to accepted safety and quality standards.",
  "Paralegal research": "Gathering and interpreting evidence using methods from this research specialty.",
  "Paramedic practice": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Patience": "Staying calm and constructive when progress is slow or outcomes are delayed.",
  "Patient intake": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Payroll administration": "Processing wages, deductions, and payroll compliance accurately.",
  "Persian": "Communicating effectively in this language or language service specialty.",
  "Persuasion": "Influencing others through reasoned argument and credible evidence.",
  "Pharmacy technician skills": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Phlebotomy": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Photography": "Creating or refining visual, product, or media work in this specialty.",
  "PHP": "Using this technology or practice to build, run, or secure digital systems.",
  "Pilot (airplane, commercial)": "Operating aircraft safely under the stated license or equipment category.",
  "Pilot (airplane, private)": "Operating aircraft safely under the stated license or equipment category.",
  "Pilot (drone / UAV)": "Operating aircraft safely under the stated license or equipment category.",
  "Pilot (helicopter)": "Operating aircraft safely under the stated license or equipment category.",
  "Pilot (instrument flight / IFR)": "Operating aircraft safely under the stated license or equipment category.",
  "Pilot (multi-engine)": "Operating aircraft safely under the stated license or equipment category.",
  "Pipefitting": "Installing or repairing piping systems for water, gas, or related services.",
  "Plumbing": "Installing or repairing piping systems for water, gas, or related services.",
  "Policy analysis": "Applying rules, research, or formal process in this legal or policy specialty.",
  "Policy drafting": "Applying rules, research, or formal process in this legal or policy specialty.",
  "Portuguese": "Communicating effectively in this language or language service specialty.",
  "Print production": "Creating or refining visual, product, or media work in this specialty.",
  "Problem solving": "Defining problems clearly and working through options to a workable solution.",
  "Process engineering": "Applying engineering or manufacturing methods in this technical specialty.",
  "Procurement": "Sourcing and purchasing goods or services under cost, quality, and policy constraints.",
  "Product design": "Creating or refining visual, product, or media work in this specialty.",
  "Product management": "Planning and coordinating work so teams deliver valued outcomes on time.",
  "Product prototyping": "Applying engineering or manufacturing methods in this technical specialty.",
  "Program evaluation": "Supporting people or civic processes through this service specialty.",
  "Project management": "Planning and coordinating work so teams deliver valued outcomes on time.",
  "Public health analysis": "Studying population health patterns to guide prevention and community health decisions.",
  "Public speaking": "Presenting ideas clearly and confidently to groups or audiences.",
  "Python": "Using this technology or practice to build, run, or secure digital systems.",
  "Qualitative research": "Gathering and interpreting evidence using methods from this research specialty.",
  "Quality assurance": "Building processes that prevent defects and maintain agreed standards.",
  "Quality control": "Inspecting outputs to catch defects before they reach users.",
  "Quantitative research": "Gathering and interpreting evidence using methods from this research specialty.",
  "Radiography": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "React": "Using this technology or practice to build, run, or secure digital systems.",
  "Records management": "Controlling how documents are created, stored, retained, and disposed.",
  "Regulatory affairs": "Applying rules, research, or formal process in this legal or policy specialty.",
  "Reliability": "Doing what you said you would do, on time and to an expected standard.",
  "Requirements gathering": "Planning and coordinating work so teams deliver valued outcomes on time.",
  "Research": "Gathering and interpreting evidence using methods from this research specialty.",
  "Resilience": "Recovering from setbacks and continuing effectively under pressure.",
  "Respectfulness": "Treating people with dignity regardless of status, disagreement, or difference.",
  "Responsibility": "Accepting duties and following through on obligations to others.",
  "Restaurant management": "Preparing food or running hospitality operations to quality and safety standards.",
  "Risk management": "Planning and coordinating work so teams deliver valued outcomes on time.",
  "Robotics": "Applying engineering or manufacturing methods in this technical specialty.",
  "Roofing": "Performing this construction or building trade to accepted safety and quality standards.",
  "Russian": "Communicating effectively in this language or language service specialty.",
  "Sailing": "Operating or working safely in this maritime or watercraft specialty.",
  "Sales operations": "Attracting, informing, or converting customers through this commercial specialty.",
  "Scaffolding": "Performing this construction or building trade to accepted safety and quality standards.",
  "Scrum mastery": "Planning and coordinating work so teams deliver valued outcomes on time.",
  "Search and rescue": "Preventing harm and responding effectively in safety or emergency situations.",
  "Security operations": "Preventing harm and responding effectively in safety or emergency situations.",
  "Self-awareness": "Recognizing your strengths, limits, emotions, and impact on others.",
  "Self-management": "Regulating time, energy, and emotions to meet commitments.",
  "SEO": "Attracting, informing, or converting customers through this commercial specialty.",
  "Servant leadership": "Leading by prioritizing others’ growth and the mission over personal status.",
  "Shipboard operations": "Operating or working safely in this maritime or watercraft specialty.",
  "Six Sigma": "Applying engineering or manufacturing methods in this technical specialty.",
  "Social media management": "Attracting, informing, or converting customers through this commercial specialty.",
  "Social work casework": "Supporting people or civic processes through this service specialty.",
  "Soil science": "Applying practical knowledge in this agricultural or environmental specialty.",
  "Spanish": "Communicating effectively in this language or language service specialty.",
  "Special education support": "Designing or delivering learning experiences in this education specialty.",
  "SQL": "Using this technology or practice to build, run, or secure digital systems.",
  "Stage production": "Practicing this performance, coaching, or creative production specialty.",
  "Stakeholder engagement": "Involving the people affected by a decision so their needs inform the outcome.",
  "Statistical analysis": "Gathering and interpreting evidence using methods from this research specialty.",
  "Storytelling": "Communicating meaning through clear, memorable narratives.",
  "Strategic planning": "Setting long-range direction and aligning near-term actions with it.",
  "Strategic planning tools": "Planning and coordinating work so teams deliver valued outcomes on time.",
  "Stress management": "Staying effective and healthy under pressure without harming others.",
  "Supply chain management": "Coordinating flow of materials and information from suppliers to delivery.",
  "Survey design": "Creating questionnaires and study instruments that collect reliable, usable information.",
  "Surveying": "Measuring land and sites with surveying instruments for maps, boundaries, and construction layout.",
  "Sustainable agriculture": "Growing food with methods that protect soil, water, biodiversity, and long-term productivity.",
  "System administration": "Using this technology or practice to build, run, or secure digital systems.",
  "Systems thinking": "Seeing how parts of a system interact and affect whole outcomes.",
  "Tax preparation": "Preparing tax filings and supporting documentation according to rules.",
  "Taxi / rideshare driving": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Teaching": "Helping others learn skills or knowledge through clear explanation and practice.",
  "Team building": "Strengthening trust, roles, and cooperation within a working group.",
  "Teamwork": "Contributing as a dependable member of a group working toward shared goals.",
  "Technical writing": "Crafting or refining text so it is clear, accurate, and fit for purpose.",
  "Theater direction": "Practicing this performance, coaching, or creative production specialty.",
  "Tile setting": "Performing this construction or building trade to accepted safety and quality standards.",
  "Time management": "Organizing tasks and priorities so important work gets done on schedule.",
  "Tractor operation": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Trailer towing": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Training delivery": "Designing or delivering learning experiences in this education specialty.",
  "Translation": "Communicating effectively in this language or language service specialty.",
  "Treasury management": "Managing cash, liquidity, and short-term financial resources.",
  "Truck driving (CDL Class A)": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Truck driving (CDL Class B)": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Truck driving (CDL Class C)": "Operating this vehicle or equipment type safely and according to applicable rules.",
  "Trust building": "Creating confidence through consistent honesty, competence, and care.",
  "Turkish": "Communicating effectively in this language or language service specialty.",
  "TypeScript": "Using this technology or practice to build, run, or secure digital systems.",
  "UI design": "Creating or refining visual, product, or media work in this specialty.",
  "UX design": "Creating or refining visual, product, or media work in this specialty.",
  "UX research": "Creating or refining visual, product, or media work in this specialty.",
  "Vaccination administration": "Applying clinical or health-support practice in this specialty with patient safety in mind.",
  "Vendor management": "Selecting, overseeing, and evaluating external suppliers and partners.",
  "Video editing": "Creating or refining visual, product, or media work in this specialty.",
  "Videography": "Creating or refining visual, product, or media work in this specialty.",
  "Volunteer coordination": "Recruiting, organizing, and supporting volunteers for meaningful work.",
  "Water resource management": "Applying practical knowledge in this agricultural or environmental specialty.",
  "Web development": "Using this technology or practice to build, run, or secure digital systems.",
  "Welding (arc)": "Joining metal using the named welding process with proper technique and safety.",
  "Welding (MIG)": "Joining metal using the named welding process with proper technique and safety.",
  "Welding (TIG)": "Joining metal using the named welding process with proper technique and safety.",
  "Wildlife management": "Applying practical knowledge in this agricultural or environmental specialty.",
  "Workplace safety auditing": "Preventing harm and responding effectively in safety or emergency situations.",
  "Workshop design": "Creating or refining visual, product, or media work in this specialty.",
  "Written communication": "Writing clearly so readers understand and can act on the message.",
  "AI engineering": "Building and integrating AI systems into products, workflows, and infrastructure.",
  "AI ethics": "Identifying and addressing fairness, accountability, privacy, and harm risks in AI use.",
  "AI evaluation / red teaming": "Testing AI systems for failures, bias, misuse, and unsafe behavior before and after release.",
  "AI literacy": "Understanding what AI can and cannot do well enough to use and judge it responsibly.",
  "AI product management": "Defining AI product requirements, success metrics, and delivery trade-offs with technical teams.",
  "AI safety": "Designing and operating AI systems to reduce harmful or unintended outcomes.",
  "AI systems design": "Architecting end-to-end AI solutions across models, data, tooling, and human oversight.",
  "Artificial intelligence (AI)": "Applying AI methods to perceive, decide, generate, or automate tasks with machine systems.",
  "Computer vision": "Teaching computers to interpret images and video for detection, classification, or measurement.",
  "Deep learning": "Training multi-layer neural networks for complex pattern recognition and prediction tasks.",
  "Feature engineering": "Creating and selecting input variables that help models learn useful patterns.",
  "Generative AI": "Using models that create text, images, code, or other content from prompts and context.",
  "Large language models (LLMs)": "Working with large text models for reasoning, generation, retrieval, and assistants.",
  "MLOps": "Operating machine-learning systems reliably across training, deployment, monitoring, and iteration.",
  "Model deployment": "Shipping trained models into production services with monitoring and rollback paths.",
  "Natural language processing (NLP)": "Processing and analyzing human language with computational methods.",
  "Neural networks": "Designing and training networked models inspired by layered representation learning.",
  "Prompt engineering": "Crafting instructions and context so generative AI systems produce reliable, useful outputs.",
  "RAG systems": "Combining retrieval with generative models so answers are grounded in selected source documents.",
  "Recommendation systems": "Building systems that suggest relevant items, people, or actions from behavioral signals.",
  "Reinforcement learning": "Training agents to improve decisions through reward feedback over time.",
  "Speech recognition / synthesis": "Converting speech to text or text to natural-sounding speech with AI models.",
};

export function getSkillDescription(name: string): string {
  const trimmed = name.trim();
  if (!trimmed) return '';
  const exact = PROFILE_SKILL_DESCRIPTIONS[trimmed];
  if (exact) return exact;
  const lower = trimmed.toLowerCase();
  for (const [key, value] of Object.entries(PROFILE_SKILL_DESCRIPTIONS)) {
    if (key.toLowerCase() === lower) return value;
  }
  return `Practical applied ability in ${trimmed}.`;
}
