/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-program-plan-summary.py — do not edit by hand. */
export const PROGRAM_PLAN_SUMMARY = {
  "modelVersion": "0.1",
  "generatedAt": "2026-08-10",
  "currency": "USD",
  "status": "non_approved_planning_estimates",
  "disclaimer": "Read-only strategic estimates and scenarios. Not approved budgets, commitments, receipts, or actual spending. Not worldwide completion or one organization\u2019s budget.",
  "hierarchy": {
    "detailedOperatingPlan": "validation_18_24_months",
    "primaryProgramPlan": "five_year_first_wave",
    "years6to10": "strategic_outlook_only",
    "years11to20": "directional_lifecycle_scenario"
  },
  "validation": {
    "status": "working_estimate",
    "durationMonths": "18-24",
    "sourceDoc": "14-pre-major-build-validation-program-v0.1.md",
    "sourceMeta": "14-validation-workstreams-and-budget-v0.1.meta.json",
    "modelVersion": "0.1",
    "updatedAt": "2026-08-10",
    "totalsUsdM": {
      "low": 202,
      "base": 446,
      "high": 898
    },
    "fundingControlBaseUsdM": {
      "core": 312,
      "independent": 34,
      "grant_pass_through": 58,
      "reserve": 42
    },
    "scenarioDiffNote": "Low: leaner staffing, fewer consultations, thinner contingency. Base: full planned workstream intensity. High: expanded consultations, demonstrators, contingency, and assurance depth.",
    "baseTranchePacing": [
      {
        "id": "T1",
        "label": "Validation launch",
        "shareOfBase": 0.25
      },
      {
        "id": "T2",
        "label": "Validation execute",
        "shareOfBase": 0.45
      },
      {
        "id": "T3",
        "label": "Validation close",
        "shareOfBase": 0.2
      },
      {
        "id": "reserve",
        "label": "Safe-pause reserve",
        "shareOfBase": 0.1
      }
    ],
    "workstreamCount": 25,
    "workstreamsDoc": "14-pre-major-build-validation-program-v0.1.md"
  },
  "fiveYearFirstWave": {
    "status": "preliminary_ecosystem_hypothesis",
    "sourceDoc": "11-program-financial-model-and-funding-responsibility-v0.1.md",
    "sourceMeta": "11-program-financial-model-v0.1.meta.json",
    "modelVersion": "0.1",
    "updatedAt": "2026-08-10",
    "rangeUsdB": {
      "lowRounded": 30,
      "highRounded": 50
    },
    "modeledBaseUsdB": 37.5,
    "modeledBaseExactUsdB": 37.51,
    "annualBaseCashflowUsdB": [
      {
        "year": 1,
        "amountUsdB": 3.0
      },
      {
        "year": 2,
        "amountUsdB": 5.25
      },
      {
        "year": 3,
        "amountUsdB": 7.5
      },
      {
        "year": 4,
        "amountUsdB": 9.75
      },
      {
        "year": 5,
        "amountUsdB": 12.0
      }
    ],
    "corePrimaryResponsibleUsdB": 4.8,
    "coreMustRaiseUsdB": 8.2,
    "notWorldwideCompletion": true,
    "notSingleOrganizationBudget": true
  },
  "longRangeOutlook": {
    "status": "internal_lifecycle_scenarios",
    "confidence": "low",
    "defaultStatement": "Years 6\u201320 are maintained as internal lifecycle scenarios and will be replaced by rolling evidence-based plans.",
    "sourceDoc": "13-ten-and-twenty-year-program-cost-framework-v0.1.md",
    "advancedDisclosureOnly": true,
    "sensitivityNote": "Highly sensitive to adoption, scope, technology, jurisdiction participation, inflation, and institutional design. Not accepted by governments, funders, or institutions. Not a budget, forecast, promise, or current funding request.",
    "scenariosUsdB": {
      "baseYears1to10": 197.5,
      "baseYears1to20": 782.5
    }
  },
  "reconciliation": {
    "validationCsvMatchesMeta": true,
    "fiveYearCashflowSumsToBase": true
  }
} as const;

export type ProgramPlanSummary = typeof PROGRAM_PLAN_SUMMARY;
