/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-program-plan-summary.py — do not edit by hand. */
export const PROGRAM_PLAN_SUMMARY = {
  "modelVersion": "0.3",
  "generatedAt": "2026-08-11",
  "currency": "USD",
  "status": "non_approved_planning_estimates",
  "disclaimer": "Read-only strategic estimates and scenarios. Not approved budgets, commitments, receipts, or actual spending. Not worldwide completion or one organization\u2019s budget. Validation Base is provisional owner-selected Recommended v0.3 exact $634.4M (~$634M); same-scope range ~$552\u2013833M pending quotations. Historical: v0.1 $446M; early v0.2 $524M; v0.2 coverage draft $530.2M. Constrained (~$374M) and Expanded (~$1.03B) are different scopes.",
  "hierarchy": {
    "detailedOperatingPlan": "validation_18_24_months",
    "primaryProgramPlan": "five_year_first_wave",
    "years6to10": "strategic_outlook_only",
    "years11to20": "directional_lifecycle_scenario"
  },
  "validation": {
    "status": "provisional_working_draft",
    "durationMonths": "18-24",
    "sourceDoc": "33-validation-scope-priority-tranche-decision.md",
    "sourceMeta": "validation-budget-v0.3.meta.json",
    "reconciliationDoc": "33-validation-scope-priority-tranche-decision.md",
    "modelVersion": "0.3.0",
    "updatedAt": "2026-08-11",
    "totalsUsdM": {
      "low": 552.4,
      "base": 634.4,
      "high": 833.2
    },
    "scopeAlternativesUsdM": {
      "constrained_different_scope": 373.8,
      "recommended_same_scope_base": 634.4,
      "expanded_different_scope": 1032.7
    },
    "historicalV01TotalsUsdM": {
      "low": 202,
      "base": 446,
      "high": 898
    },
    "historicalV02CoverageDraftUsdM": {
      "low": 438.3,
      "base": 530.2,
      "high": 654.5
    },
    "fundingControlBaseUsdM": {
      "core": 437.8,
      "independent": 36.0,
      "grant_pass_through": 94.0,
      "reserve": 66.6
    },
    "directContingencySafePauseUsdM": {
      "direct": 489.5,
      "contingency": 78.3,
      "safePause": 66.6
    },
    "scenarioDiffNote": "Same-scope Low (~$552.4M) / Base (exact $634.4M / ~$634M) / High (~$833.2M): unit-cost and quotation variance for the Recommended deliverable set \u2014 not scope cuts. Constrained (~$373.8M) and Expanded (~$1.0327B) are different scopes and must not be presented as equally capable cheaper/same programs. VAL-EX16 is quote-dependent. Historical: v0.1 $446M; early v0.2 $524M; v0.2 coverage $530.2M.",
    "baseTranchePacing": [
      {
        "id": "T1",
        "label": "Formation & quotation (first required legal commitment ~$132M)",
        "shareOfBase": 0.2081,
        "indicativeDirectUsdM": 132.0
      },
      {
        "id": "T2",
        "label": "Core research & design",
        "shareOfBase": 0.2305,
        "indicativeDirectUsdM": 146.2
      },
      {
        "id": "T3",
        "label": "Participation & domain studies",
        "shareOfBase": 0.2278,
        "indicativeDirectUsdM": 144.5
      },
      {
        "id": "T5",
        "label": "Independent assurance",
        "shareOfBase": 0.0599,
        "indicativeDirectUsdM": 38.0
      },
      {
        "id": "T4",
        "label": "Controlled prototypes (after insurance bind path)",
        "shareOfBase": 0.0454,
        "indicativeDirectUsdM": 28.8
      },
      {
        "id": "T6",
        "label": "Safe-pause & continuity (tranche-specific)",
        "shareOfBase": 0.2284,
        "indicativeDirectUsdM": 144.9
      }
    ],
    "fundingControlsNote": "Distinguish expression of interest, pledge, conditional commitment, legally binding commitment, received cash, escrowed cash, and available cash. Do not begin T1 on nonbinding interest alone. Initial received/escrowed working floor provisional $60M. No obligations dependent on an uncommitted later tranche. Insurance binding or an approved binding path before field activity. Receiving-entity path unresolved \u2014 do not accept funds until authorized.",
    "workstreamCount": 53,
    "groupCount": 13,
    "workstreamsDoc": "33-validation-scope-priority-tranche-decision.md",
    "appBudgetName": "Civizen Pre-Major-Build Validation Program v0.3"
  },
  "fiveYearFirstWave": {
    "status": "preliminary_ecosystem_hypothesis",
    "sourceDoc": "11-program-financial-model-and-funding-responsibility-v0.1.md",
    "sourceMeta": "11-program-financial-model-v0.1.meta.json",
    "modelVersion": "0.1",
    "updatedAt": "2026-08-10",
    "rangeUsdB": {
      "lowRounded": 30,
      "highRounded": 50
    },
    "modeledBaseUsdB": 37.5,
    "modeledBaseExactUsdB": 37.51,
    "reconciledBaseUsdB": "37.5-38.0",
    "annualBaseCashflowUsdB": [
      {
        "year": 1,
        "amountUsdB": 3.0
      },
      {
        "year": 2,
        "amountUsdB": 5.25
      },
      {
        "year": 3,
        "amountUsdB": 7.5
      },
      {
        "year": 4,
        "amountUsdB": 9.75
      },
      {
        "year": 5,
        "amountUsdB": 12.0
      }
    ],
    "corePrimaryResponsibleUsdB": 4.8,
    "coreMustRaiseUsdB": 8.2,
    "notWorldwideCompletion": true,
    "notSingleOrganizationBudget": true,
    "domainLayers": {
      "frameworkVsDeployment": "SD-* lines are shared frameworks/standards only. Domain production deployment is attributed inside JP/II, not added on top of SD-*.",
      "health": {
        "frameworkSdHeaUsdM": 280,
        "jpIiProvisionalDeploymentUsdM": 1870,
        "jpIiShareOf17bPct": 11,
        "notWorldwideHealthImplementation": true,
        "confidence": "low",
        "quoteRequired": true
      },
      "insuranceSystems": {
        "sdInsFrameworkUsdM": 120,
        "fundingSource": "carve_from_SD-FIN_80_plus_SD-ADD_40",
        "sdFinAfterCarveUsdM": 270,
        "sdAddAfterCarveUsdM": 90,
        "jpIiProvisionalIntegrationUsdM": 680,
        "jpIiShareOf17bPct": 4,
        "notUnderwriterOrClaimsStore": true,
        "confidence": "low",
        "quoteRequired": true
      },
      "responsibility": {
        "shared": "frameworks, standards, federation patterns, independent assurance",
        "jurisdictionalInstitutional": "local adaptation, production systems, clinical/insurance operation"
      }
    }
  },
  "longRangeOutlook": {
    "status": "internal_lifecycle_scenarios",
    "confidence": "low",
    "defaultStatement": "Years 6\u201320 are maintained as internal lifecycle scenarios and will be replaced by rolling evidence-based plans.",
    "sourceDoc": "13-ten-and-twenty-year-program-cost-framework-v0.1.md",
    "advancedDisclosureOnly": true,
    "sensitivityNote": "Highly sensitive to adoption, scope, technology, jurisdiction participation, inflation, and institutional design. Not accepted by governments, funders, or institutions. Not a budget, forecast, promise, or current funding request.",
    "scenariosUsdB": {
      "baseYears1to10": 197.5,
      "baseYears1to20": 782.5
    }
  },
  "reconciliation": {
    "historicalValidationCsvMatchesMetaV01": true,
    "validationWorkingDraft": "v0.3",
    "fiveYearCashflowSumsToBase": true,
    "sdInsCarveNetZeroToFiveYearTotal": true
  }
} as const;

export type ProgramPlanSummary = typeof PROGRAM_PLAN_SUMMARY;
