/**
 * Canonical Draft Budget structure for Civizen Pre-Major-Build Validation Program v0.3.
 * Owner-selected Recommended Validation Program from decision pack docs/04-operations/funding-and-budget/33-*.
 * Exact Base $634,400,000.00. Preserves v0.1 and v0.2 as historical/superseded.
 * Committed and actual are always 0. Not approved / not published.
 */

export const VALIDATION_BUDGET_V03 = {
  name: 'Civizen Pre-Major-Build Validation Program v0.3',
  version: 1,
  currency: 'USD',
  purpose:
    'Provisional owner-selected Recommended Validation Program (docs 33). Exact Base $634,400,000.00 (~$634M). Same-scope planning range ~$552–833M pending quotations. Not an approved budget, bid, commitment, or authorization to accept funds. Receiving-entity path unresolved.',
  internalNotes:
    'Selected Recommended case from doc 33. Direct $489.5M + contingency $78.3M + safe-pause $66.6M = $634.4M. VAL-EX16 quote-dependent. Historical: v0.1 $446M; early v0.2 proposal $524M; v0.2 coverage draft $530.2M. Constrained ~$374M and Expanded ~$1.03B are different scopes. FPP unchanged.',
  isDemonstration: false,
  lifecycleStatus: 'draft' as const,
  plannedTotalMinor: 63_440_000_000,
  plannedTotalUsd: 634_400_000,
  supersedesName: 'Civizen Pre-Major-Build Validation Program v0.2',
} as const;

export type ValidationFundingControlV03 = 'core' | 'independent' | 'grant_pass_through' | 'reserve';

export type ValidationBudgetGroupV03 = {
  key: string;
  name: string;
  description: string;
  displayOrder: number;
};

export const VALIDATION_BUDGET_GROUPS_V03: readonly ValidationBudgetGroupV03[] = [
  {
    key: 'program_office',
    name: 'Program office & coordination',
    description: 'Core stewardship, workforce administration, public documentation, and travel/fieldwork coordination.',
    displayOrder: 10,
  },
  {
    key: 'constitutional_rights_legal',
    name: 'Constitutional, rights & legal formation',
    description: 'Institutional design, anti-capture safeguards, and legal entity formation.',
    displayOrder: 20,
  },
  {
    key: 'inventory_architecture',
    name: 'Inventory, architecture & federation',
    description: 'System-catalog validation, architecture/threat work, validation tech tooling, and operator-network design.',
    displayOrder: 30,
  },
  {
    key: 'privacy_security_ai',
    name: 'Privacy, security & AI assurance',
    description: 'Privacy/data governance, security research, and AI governance frameworks.',
    displayOrder: 40,
  },
  {
    key: 'identity_econ_standards',
    name: 'Identity, economics, standards & inclusion',
    description: 'Identity interoperability, economic feasibility, standards, and accessibility/localization.',
    displayOrder: 50,
  },
  {
    key: 'domain_studies',
    name: 'Domain studies & consultations',
    description: 'Named priority domain studies (WS-12.1–12.10), coordination, and jurisdiction consultations.',
    displayOrder: 60,
  },
  {
    key: 'independent_review',
    name: 'Independent multidisciplinary review',
    description: 'Ring-fenced independent panels and secretariat.',
    displayOrder: 70,
  },
  {
    key: 'demos_cost_validation',
    name: 'Controlled prototypes & cost validation',
    description: 'Controlled non-authoritative prototypes, hosting/shutdown, supplier evidence, and research licensing.',
    displayOrder: 80,
  },
  {
    key: 'procurement_controls',
    name: 'Procurement & financial controls',
    description: 'Procurement setup plus accounting, audit readiness, and payment controls.',
    displayOrder: 90,
  },
  {
    key: 'explicit_opex',
    name: 'Explicit operating provisions',
    description: 'Workforce benefits gap, quote-dependent program insurance, treasury/tax/facilities, emergency assistance (v0.3 Recommended).',
    displayOrder: 100,
  },
  {
    key: 'grants_civil_society',
    name: 'Grants & civil-society participation',
    description: 'Grants to research institutions and civil-society participants.',
    displayOrder: 110,
  },
  {
    key: 'contingency',
    name: 'Program contingency',
    description: 'Policy contingency recalculated once (~16% of Recommended direct $489.5M).',
    displayOrder: 120,
  },
  {
    key: 'safe_pause_reserve',
    name: 'Safe-pause reserve',
    description: 'Safe-pause continuity (once-recalc) plus incident response/decommissioning slice.',
    displayOrder: 130,
  },
]

export type ValidationBudgetLineV03 = {
  workstreamId: string;
  groupKey: string;
  title: string;
  description: string;
  publicDescription: string;
  baseUsdM: number;
  plannedMinor: number;
  committedMinor: 0;
  actualMinor: 0;
  currency: "USD";
  periodLabel: string;
  publishFlag: false;
  fundingControl: ValidationFundingControlV03;
  ownerLabel: string;
};

function usdMToMinor(usdM: number): number {
  return Math.round(usdM * 1_000_000 * 100);
}

function periodLabel(start: number, duration: number): string {
  const end = start + duration - 1;
  return `Months ${start}–${end} · working estimate`;
}

export const VALIDATION_BUDGET_LINES_V03: readonly ValidationBudgetLineV03[] = [
  {
    workstreamId: 'WS-01',
    groupKey: 'program_office',
    title: 'WS-01 · Core multidisciplinary program office & stewardship teams',
    description:
      'Primary EX-01/EX-13. Loaded FTE/contractor stewardship. Includes embedded EX-02 benefits slice (~$25.9M disclosed across personnel-heavy lines; not additive here). Excludes WS-01.ADM (split).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 28,
    plannedMinor: usdMToMinor(28),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-01.ADM',
    groupKey: 'program_office',
    title: 'WS-01.ADM · Recruitment, onboarding, training, background checks & workforce administration',
    description:
      'Traceable split from WS-01 ($28M→$26M+$2M). Primary EX-13/EX-19. Recruitment, onboarding, training, and workforce administration. Role-based screening/safeguarding depth beyond this slice is VAL-SCR (additive — not double-counted).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 2.5,
    plannedMinor: usdMToMinor(2.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'VAL-SCR',
    groupKey: 'program_office',
    title: 'VAL-SCR · Role-based screening, safeguarding & background checks',
    description:
      'Additive EX-13/EX-19 depth beyond WS-01.ADM. Role-specific, proportionate, purpose-limited screening and safeguarding checks for defined validation roles; appealable where relevant; compliant with applicable rights and employment law. Not universal participant screening.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 1.5,
    plannedMinor: usdMToMinor(1.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-21',
    groupKey: 'program_office',
    title: 'WS-21 · Public documentation & transparency program',
    description:
      'Primary EX-21. Public documentation, transparency artifacts, and communications for the validation program (not broad marketing spend).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 7,
    plannedMinor: usdMToMinor(7),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-22',
    groupKey: 'program_office',
    title: 'WS-22 · Travel, fieldwork & international coordination',
    description:
      'Corrected Recommended travel book (doc 33): ~450 person-trips at ~$5k loaded traveler costs plus logistics, accessible travel, equity routing, disruption. Primary EX-22. Events→VAL-EVT; insurance premiums→VAL-EX16; staff pay→WS-01.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 11.5,
    plannedMinor: usdMToMinor(11.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-02',
    groupKey: 'constitutional_rights_legal',
    title: 'WS-02 · Constitutional & institutional design',
    description:
      'Primary EX-14. Constitutional and institutional design for validation-phase governance frameworks.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 18,
    plannedMinor: usdMToMinor(18),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-03',
    groupKey: 'constitutional_rights_legal',
    title: 'WS-03 · Human-rights & anti-capture safeguards',
    description:
      'Primary EX-14. Human-rights review, anti-capture safeguards, and related ethics work.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 12,
    plannedMinor: usdMToMinor(12),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-18',
    groupKey: 'constitutional_rights_legal',
    title: 'WS-18 · Legal entity & organizational formation package',
    description:
      'Primary EX-15/EX-03. Entity formation, corporate counsel, regulatory filings setup. Ongoing accounting/audit ops clarified under WS-19.FIN (split from WS-19).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 16,
    plannedMinor: usdMToMinor(16),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-04',
    groupKey: 'inventory_architecture',
    title: 'WS-04 · System-inventory validation campaign (467 entries)',
    description:
      'Primary EX-04. Challenges and validates the 467-entry system catalog; research/data acquisition for inventory rows included.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 15,
    plannedMinor: usdMToMinor(15),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(2, 18),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-05',
    groupKey: 'inventory_architecture',
    title: 'WS-05 · Architecture alternatives & threat modeling',
    description:
      'Primary EX-05/EX-07. Architecture alternatives and threat modeling labor. Cloud/tooling/security tooling carved to WS-05.TEC (split from prior $22M).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 18,
    plannedMinor: usdMToMinor(18),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 20),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-05.TEC',
    groupKey: 'inventory_architecture',
    title: 'WS-05.TEC · Cloud, communications, AI/API use, research tooling & security tooling',
    description:
      'Traceable split from WS-05 ($22M→$17M+$5M). Primary EX-05/EX-06/EX-08/EX-18. Validation-phase cloud/hosting for research, communications infra, AI/API usage, specialist research tools, and security tooling (non-production).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 7,
    plannedMinor: usdMToMinor(7),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 20),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-06',
    groupKey: 'inventory_architecture',
    title: 'WS-06 · Federation & operator-network design validation',
    description:
      'Primary EX-10. Design validation of federation/operator-network models — not funding 100 production operators.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 16,
    plannedMinor: usdMToMinor(16),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(4, 18),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-07',
    groupKey: 'privacy_security_ai',
    title: 'WS-07 · Privacy & data-governance design',
    description:
      'Primary EX-07. Privacy/data-governance design, DPIA methods, and related assurance research.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 12,
    plannedMinor: usdMToMinor(12),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(2, 18),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-08',
    groupKey: 'privacy_security_ai',
    title: 'WS-08 · Security & cryptographic research',
    description:
      'Primary EX-07. Security and cryptographic research (methods, threat models, test suites). Premium purchase is VAL-EX16; tooling spend also in WS-05.TEC / WS-17.HST.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 18,
    plannedMinor: usdMToMinor(18),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(2, 20),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-09',
    groupKey: 'privacy_security_ai',
    title: 'WS-09 · AI governance & assurance frameworks',
    description:
      'Primary EX-06/EX-07. AI governance and assurance frameworks; model-eval methods. AI/API usage budget home includes WS-05.TEC.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 11,
    plannedMinor: usdMToMinor(11),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(3, 18),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-10',
    groupKey: 'identity_econ_standards',
    title: 'WS-10 · Identity & credential interoperability validation',
    description:
      'Identity & credential interoperability validation (doc 33): ~8–12 jurisdictions; design/interop only — not national ID issuance or population binding. Primary EX-05/EX-12.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 14,
    plannedMinor: usdMToMinor(14),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(3, 18),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-11',
    groupKey: 'identity_econ_standards',
    title: 'WS-11 · Economic, payments, accounting & taxation feasibility',
    description:
      'Primary EX-04/EX-15. Feasibility of economic/payments/accounting/tax hooks — not live rails. Live banking/FX OpEx is VAL-EX17; tax charges VAL-EX28.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 14,
    plannedMinor: usdMToMinor(14),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(4, 18),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-14',
    groupKey: 'identity_econ_standards',
    title: 'WS-14 · Standards & interoperability planning',
    description:
      'Primary EX-12. Standards and interoperability planning; conformance test-suite seeds.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 9,
    plannedMinor: usdMToMinor(9),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(4, 18),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-15',
    groupKey: 'identity_econ_standards',
    title: 'WS-15 · Accessibility, localization & nondigital inclusion validation',
    description:
      'Recommended Validation sample (doc 33): ~12–16 languages; indigenous/sign/nondigital patterns. Primary EX-20. NOT every language/country. Label: Accessibility, localization & nondigital inclusion validation.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 18,
    plannedMinor: usdMToMinor(18),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(3, 20),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-12.1',
    groupKey: 'domain_studies',
    title: 'WS-12.1 · Health — systems, public health, clinical safety, medicines, workforce, data & financing',
    description:
      'Commissioned Health-system validation study (EX-04). Health systems, public health, clinical safety, medicines, workforce interfaces, health data, financing. Includes study-local research data, specialist tools, participant compensation, and publication prep. Role = standards/integration — not clinical operator or insurer. Distinct from VAL-EX02-GAP (employer benefits OpEx).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 10,
    plannedMinor: usdMToMinor(10),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(3, 20),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'WS-12.2',
    groupKey: 'domain_studies',
    title: 'WS-12.2 · Justice and dispute-resolution systems study',
    description:
      'Commissioned domain study (EX-04). Includes study research data, specialist input, participant compensation, and publication prep.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 6,
    plannedMinor: usdMToMinor(6),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(3, 20),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'WS-12.3',
    groupKey: 'domain_studies',
    title: 'WS-12.3 · Tax and public-revenue systems study',
    description:
      'Commissioned domain study (EX-04). Hooks/feasibility — not tax authority. Study research/data/publication included.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 4,
    plannedMinor: usdMToMinor(4),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(4, 17),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'WS-12.4',
    groupKey: 'domain_studies',
    title: 'WS-12.4 · Insurance — finance, banking, payments & monetary interfaces',
    description:
      'Commissioned Insurance-system validation study (EX-04). Finance, banking, insurance-system frameworks, payments, monetary interfaces. Includes study research data, specialist tools, participant compensation, publications. Distinct from VAL-EX16 (program insurance OpEx). Role = standards/integration — not underwriter.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 9,
    plannedMinor: usdMToMinor(9),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(3, 20),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'WS-12.5',
    groupKey: 'domain_studies',
    title: 'WS-12.5 · Migration, borders, residency & mobility study',
    description:
      'Commissioned domain study (EX-04). Study research/data/participant/publication costs included.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 6,
    plannedMinor: usdMToMinor(6),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(3, 20),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'WS-12.6',
    groupKey: 'domain_studies',
    title: 'WS-12.6 · Elections and democratic participation study',
    description:
      'Commissioned domain study (EX-04). Non-binding research only. Study research/data/participant/publication costs included.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 5,
    plannedMinor: usdMToMinor(5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(4, 18),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'WS-12.7',
    groupKey: 'domain_studies',
    title: 'WS-12.7 · Social protection, children, disability, pensions & care study',
    description:
      'Commissioned domain study (EX-04). Study research/data/participant/publication costs included.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 5.5,
    plannedMinor: usdMToMinor(5.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(4, 18),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'WS-12.8',
    groupKey: 'domain_studies',
    title: 'WS-12.8 · Land, housing, property, communal & Indigenous rights study',
    description:
      'Commissioned domain study (EX-04). FPIC-sensitive methods; study research/data/participant/publication costs included.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 7,
    plannedMinor: usdMToMinor(7),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(3, 20),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'WS-12.9',
    groupKey: 'domain_studies',
    title: 'WS-12.9 · Energy, environment & nuclear-accounting boundaries study',
    description:
      'Commissioned domain study (EX-04). Boundary research; nuclear custody excluded. Study research/data/publication included.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 4.5,
    plannedMinor: usdMToMinor(4.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(4, 17),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'WS-12.10',
    groupKey: 'domain_studies',
    title: 'WS-12.10 · Official statistics, measurement & public evidence study',
    description:
      'Commissioned domain study (EX-04). Not becoming an NSO. Study research/data/publication included.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 4.5,
    plannedMinor: usdMToMinor(4.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(4, 17),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'WS-12.C',
    groupKey: 'domain_studies',
    title: 'WS-12.C · Domain-study coordination & synthesis',
    description:
      'Primary EX-04/EX-13. Cross-study coordination and synthesis — not an equal residual of the former $32M envelope.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 5,
    plannedMinor: usdMToMinor(5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(3, 22),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-13',
    groupKey: 'domain_studies',
    title: 'WS-13 · Jurisdiction & institutional consultations',
    description:
      'Primary EX-11/EX-21. Jurisdiction and institutional consultations, convenings, and related participant/host compensation (distinct from WS-23 grants).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 26,
    plannedMinor: usdMToMinor(26),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(2, 23),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-16',
    groupKey: 'independent_review',
    title: 'WS-16 · Independent multidisciplinary review panels (16)',
    description:
      'Primary EX-04/EX-14. Ring-fenced independent panels and secretariat; includes Health panel among others.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 36,
    plannedMinor: usdMToMinor(36),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'independent',
    ownerLabel: 'Independent review',
  },
  {
    workstreamId: 'WS-17',
    groupKey: 'demos_cost_validation',
    title: 'WS-17 · Controlled non-authoritative prototypes',
    description:
      'Primary EX-05. Controlled non-authoritative prototypes (synthetic/authorized test data); labeled and stoppable. Hosting/security tooling/shutdown carved to WS-17.HST. Insurance gate: VAL-EX16 before multi-party prototypes.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 24,
    plannedMinor: usdMToMinor(24),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(6, 18),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-17.HST',
    groupKey: 'demos_cost_validation',
    title: 'WS-17.HST · Prototype hosting, security tooling & controlled shutdown/decommissioning',
    description:
      'Traceable split from WS-17 ($24M→$21M+$3M). Primary EX-08/EX-27/EX-30-05. Prototype hosting, security tooling, controlled shutdown, and data export for prototype environments. Broader secure disposal/e-waste is VAL-DISP (additive — not double-counted).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 4,
    plannedMinor: usdMToMinor(4),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(6, 18),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-20',
    groupKey: 'demos_cost_validation',
    title: 'WS-20 · Supplier evidence & cost validation',
    description:
      'Primary EX-04. RFI/quotes/actuarial/benchmarks challenging planning hypotheses. Licensing/data tools carved to WS-20.LIC. Does not purchase insurance cover (VAL-EX16).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 11,
    plannedMinor: usdMToMinor(11),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(6, 18),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-20.LIC',
    groupKey: 'demos_cost_validation',
    title: 'WS-20.LIC · Data acquisition, specialist research tools, publications & licensing',
    description:
      'Traceable split from WS-20 ($10M→$8M+$2M). Primary EX-18/EX-04. Data acquisition, specialist research tools, publications, and software/data licensing for validation evidence work.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 2.5,
    plannedMinor: usdMToMinor(2.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(6, 18),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'VAL-DISP',
    groupKey: 'demos_cost_validation',
    title: 'VAL-DISP · Secure disposal & e-waste handling',
    description:
      'Additive EX-09/EX-25 beyond WS-17.HST prototype disposal and VAL-EX09-GAP facilities. Secure disposal, crypto-erase where required, and e-waste handling for validation equipment and media. Not double-counted with WS-17.HST.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 0.8,
    plannedMinor: usdMToMinor(0.8),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'VAL-UTIL',
    groupKey: 'demos_cost_validation',
    title: 'VAL-UTIL · Utilities & energy for validation compute',
    description:
      'Additive EX-25. Utilities and energy for validation-phase compute and research environments — beyond thin embeds in cloud/tooling lines.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 0.7,
    plannedMinor: usdMToMinor(0.7),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-19',
    groupKey: 'procurement_controls',
    title: 'WS-19 · Procurement & financial-control systems setup',
    description:
      'Primary EX-18/EX-15. Procurement and multi-entity financial-control systems setup. Accounting/audit/treasury ops carved to WS-19.FIN.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 6,
    plannedMinor: usdMToMinor(6),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 12),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-19.FIN',
    groupKey: 'procurement_controls',
    title: 'WS-19.FIN · Accounting, independent financial audit, tax compliance & payment controls',
    description:
      'Traceable split from WS-19 ($7M→$5M+$2M). Primary EX-03/EX-15/EX-17. Accounting setup, audit readiness, tax compliance processes, and payment-control operations. Recurring independent financial audit fees are VAL-AUD (additive — not double-counted). Live FX/fees also VAL-EX17.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 2.5,
    plannedMinor: usdMToMinor(2.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 12),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'VAL-AUD',
    groupKey: 'procurement_controls',
    title: 'VAL-AUD · Recurring independent financial audit',
    description:
      'Additive EX-03/EX-07 beyond WS-19.FIN setup. Recurring independent financial audit fees for the validation phase — not formation-only accounting setup.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 2,
    plannedMinor: usdMToMinor(2),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'VAL-EX02-GAP',
    groupKey: 'explicit_opex',
    title: 'VAL-EX02-GAP · Workforce health, benefits, safety & wellbeing (EX-02 gap)',
    description:
      'Explicit EX-02 additive gap beyond loaded personnel: employer health/jurisdictional equivalent uplift, disability/life, OHS, mental health/EAP, workers’ compensation equivalents, leave/statutory, contractor/participant duty-of-care. Embedded ~$25.9M remains inside personnel-heavy WS totals (disclosure only — not added twice).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 7,
    plannedMinor: usdMToMinor(7),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'VAL-EX16',
    groupKey: 'explicit_opex',
    title: 'VAL-EX16 · Program insurance & liability (EX-16 · quote-dependent)',
    description:
      'QUOTE-DEPENDENT planning allowance (doc 33) — NOT validated coverage. D&O, E&O, cyber, GL, EPL, travel/medical, participant, prototype, property, SIR. Bind or formal waiver required before field/multi-party prototypes.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 12,
    plannedMinor: usdMToMinor(12),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'VAL-EX17',
    groupKey: 'explicit_opex',
    title: 'VAL-EX17 · Banking, treasury & foreign-exchange costs (EX-17)',
    description:
      'Explicit EX-17. Bank/payment processing fees, treasury/custody, and FX conversion costs for the validation phase.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 1.5,
    plannedMinor: usdMToMinor(1.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'VAL-EX28',
    groupKey: 'explicit_opex',
    title: 'VAL-EX28 · Taxes, duties & mandatory charges (EX-28)',
    description:
      'Explicit EX-28. Taxes, duties, assessments, and mandatory charges not absorbed in loaded FTE.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 1.5,
    plannedMinor: usdMToMinor(1.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'VAL-EX09-GAP',
    groupKey: 'explicit_opex',
    title: 'VAL-EX09-GAP · Facilities, equipment, supplies & secure asset disposal (EX-09 gap)',
    description:
      'Explicit EX-09 gap beyond thin embeds in WS-01: offices/facilities, equipment/devices, supplies, and secure asset disposal / e-waste compliance for validation ops.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 2.5,
    plannedMinor: usdMToMinor(2.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'VAL-EMR',
    groupKey: 'explicit_opex',
    title: 'VAL-EMR · Emergency participant/field assistance',
    description:
      'Additive EX-27 cash/ops fund distinct from WS-25.IR and VAL-EX16 insurance. Defined purpose: emergency participant/field assistance during authorized validation activities. Eligibility rule, authorization process, evidence requirement, and audit trail required — not discretionary cash.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 1.5,
    plannedMinor: usdMToMinor(1.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'VAL-LOSS',
    groupKey: 'explicit_opex',
    title: 'VAL-LOSS · Refunds, reversals, bad debt & loss adjustments',
    description:
      'Additive EX-29. Refunds, reversals, bad-debt expense, and loss adjustments arising in validation-phase financial operations. Not contingency and not safe-pause.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 0.5,
    plannedMinor: usdMToMinor(0.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-23',
    groupKey: 'grants_civil_society',
    title: 'WS-23 · Grants to research institutions & civil-society participants',
    description:
      'Primary EX-23. Grants and participant compensation to research institutions and civil-society participants (events/consultations also touch WS-13 / study lines).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 30,
    plannedMinor: usdMToMinor(30),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(2, 23),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'VAL-EVT',
    groupKey: 'grants_civil_society',
    title: 'VAL-EVT · Convenings, consultations & events beyond travel',
    description:
      'Additive EX-21/EX-22-02 beyond WS-22 travel logistics and WS-13 consultation labor. Convenings, consultations, and events (venue, facilitation, participant support for events) owned with civil-society/grants coordination. Airfare/lodging/visas/per diem/ground/logistics/travel safety remain WS-22.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 2.5,
    plannedMinor: usdMToMinor(2.5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(2, 23),
    publishFlag: false,
    fundingControl: 'grant_pass_through',
    ownerLabel: 'Grants / pass-through',
  },
  {
    workstreamId: 'WS-24',
    groupKey: 'contingency',
    title: 'WS-24 · Program contingency (policy)',
    description:
      'Primary EX-30-01. Contingency recalculated once at ~16% of Recommended direct work program ($489.5M) → $78.3M. Not insurance; not safe-pause.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 78.3,
    plannedMinor: usdMToMinor(78.3),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'core',
    ownerLabel: 'Core-controlled',
  },
  {
    workstreamId: 'WS-25',
    groupKey: 'safe_pause_reserve',
    title: 'WS-25 · Safe-pause & validation-program continuity reserve',
    description:
      'Primary EX-30-04. Safe-pause core after once-recalc (~13.6% of $489.5M direct minus WS-25.IR). Validation wind-down/publish/archive only — not production continuity $2–4B.',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 61.6,
    plannedMinor: usdMToMinor(61.6),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'reserve',
    ownerLabel: 'Protected reserve',
  },
  {
    workstreamId: 'WS-25.IR',
    groupKey: 'safe_pause_reserve',
    title: 'WS-25.IR · Incident response, emergency assistance & demonstrator decommissioning',
    description:
      'Incident response & demonstrator decommissioning within safe-pause group (doc 33 Recommended $5.0M).',
    publicDescription: 'Working estimate — not published financial figures.',
    baseUsdM: 5,
    plannedMinor: usdMToMinor(5),
    committedMinor: 0,
    actualMinor: 0,
    currency: 'USD',
    periodLabel: periodLabel(1, 24),
    publishFlag: false,
    fundingControl: 'reserve',
    ownerLabel: 'Protected reserve',
  },
];

export function summarizeValidationBudgetV03() {
  const plannedMinor = VALIDATION_BUDGET_LINES_V03.reduce((s, l) => s + l.plannedMinor, 0);
  return {
    groupCount: VALIDATION_BUDGET_GROUPS_V03.length,
    lineCount: VALIDATION_BUDGET_LINES_V03.length,
    plannedMinor,
    plannedUsd: plannedMinor / 100,
  };
}
