import type { FulfillmentIntervention, FulfillmentSupportOption } from './types';
import { FULFILLMENT_LIBRARY_VERSION } from './types';

const v = FULFILLMENT_LIBRARY_VERSION;

export const FULFILLMENT_INTERVENTIONS: FulfillmentIntervention[] = [
  {
    key: 'time-one-evening',
    domains: ['time_life_balance'],
    causeGroups: ['time'],
    factorTags: ['overwork', 'no_rest', 'commute'],
    type: 'self_directed',
    titleKey: 'happiness.plans.library.timeEvening.title',
    descriptionKey: 'happiness.plans.library.timeEvening.body',
    effort: 'low',
    relatedPath: null,
    version: v,
  },
  {
    key: 'time-commute-system',
    domains: ['time_life_balance', 'environment_community'],
    factorTags: ['commute'],
    type: 'community_system',
    titleKey: 'happiness.plans.library.commuteSystem.title',
    descriptionKey: 'happiness.plans.library.commuteSystem.body',
    effort: 'moderate',
    relatedPath: '/contribute/challenges',
    cautionKey: 'happiness.plans.library.commuteSystem.caution',
    version: v,
  },
  {
    key: 'relationships-reach',
    domains: ['relationships_belonging'],
    causeGroups: ['relationships'],
    type: 'social_community',
    titleKey: 'happiness.plans.library.relationshipsReach.title',
    descriptionKey: 'happiness.plans.library.relationshipsReach.body',
    effort: 'low',
    relatedPath: '/contribute',
    supportType: 'peer_community',
    version: v,
  },
  {
    key: 'health-rest',
    domains: ['health_vitality'],
    causeGroups: ['health'],
    factorTags: ['sleep', 'energy', 'insufficient_rest'],
    type: 'routine_environment',
    titleKey: 'happiness.plans.library.healthRest.title',
    descriptionKey: 'happiness.plans.library.healthRest.body',
    effort: 'low',
    relatedPath: null,
    version: v,
  },
  {
    key: 'health-professional',
    domains: ['health_vitality', 'emotional_wellbeing'],
    causeGroups: ['health'],
    type: 'expert_support',
    titleKey: 'happiness.plans.library.healthProfessional.title',
    descriptionKey: 'happiness.plans.library.healthProfessional.body',
    effort: 'moderate',
    relatedPath: null,
    supportType: 'health_resource',
    cautionKey: 'happiness.plans.healthBoundary',
    version: v,
  },
  {
    key: 'purpose-contribute',
    domains: ['meaning_purpose', 'life_satisfaction'],
    causeGroups: ['purpose'],
    type: 'contribution',
    titleKey: 'happiness.plans.library.purposeContribute.title',
    descriptionKey: 'happiness.plans.library.purposeContribute.body',
    effort: 'moderate',
    relatedPath: '/contribute',
    version: v,
  },
  {
    key: 'security-next',
    domains: ['security_stability'],
    causeGroups: ['security'],
    type: 'financial_security',
    titleKey: 'happiness.plans.library.securityNext.title',
    descriptionKey: 'happiness.plans.library.securityNext.body',
    effort: 'low',
    relatedPath: null,
    version: v,
  },
  {
    key: 'security-human-support',
    domains: ['security_stability'],
    causeGroups: ['security'],
    type: 'expert_support',
    titleKey: 'happiness.plans.library.securitySupport.title',
    descriptionKey: 'happiness.plans.library.securitySupport.body',
    effort: 'moderate',
    relatedPath: null,
    supportType: 'financial_service',
    version: v,
  },
  {
    key: 'environment-community',
    domains: ['environment_community'],
    type: 'community_system',
    titleKey: 'happiness.plans.library.environmentCommunity.title',
    descriptionKey: 'happiness.plans.library.environmentCommunity.body',
    effort: 'moderate',
    relatedPath: '/contribute/challenges',
    cautionKey: 'happiness.plans.library.environmentCommunity.caution',
    version: v,
  },
  {
    key: 'life-one-area',
    domains: ['life_satisfaction', 'emotional_wellbeing'],
    type: 'reflection',
    titleKey: 'happiness.plans.library.lifeOneArea.title',
    descriptionKey: 'happiness.plans.library.lifeOneArea.body',
    effort: 'low',
    relatedPath: null,
    version: v,
  },
  {
    key: 'emotional-with-person',
    domains: ['emotional_wellbeing', 'relationships_belonging'],
    type: 'expert_support',
    titleKey: 'happiness.plans.library.emotionalPerson.title',
    descriptionKey: 'happiness.plans.library.emotionalPerson.body',
    effort: 'moderate',
    relatedPath: null,
    supportType: 'friend_family',
    cautionKey: 'happiness.plans.healthBoundary',
    version: v,
  },
  {
    key: 'autonomy-study',
    domains: ['autonomy_freedom', 'meaning_purpose'],
    type: 'learning',
    titleKey: 'happiness.plans.library.autonomyStudy.title',
    descriptionKey: 'happiness.plans.library.autonomyStudy.body',
    effort: 'moderate',
    relatedPath: '/study',
    supportType: 'learning_program',
    version: v,
  },
  {
    key: 'autonomy-one-choice',
    domains: ['autonomy_freedom'],
    type: 'self_directed',
    titleKey: 'happiness.plans.library.autonomyChoice.title',
    descriptionKey: 'happiness.plans.library.autonomyChoice.body',
    effort: 'low',
    relatedPath: '/happiness/work',
    version: v,
  },
  {
    key: 'work-open-workspace',
    domains: ['work_fulfillment'],
    causeGroups: ['work'],
    factorTags: ['tasks', 'workload', 'manager', 'team', 'schedule', 'poor_fit', 'lack_of_autonomy', 'lack_of_purpose'],
    type: 'work_fulfillment',
    titleKey: 'happiness.plans.library.workDelegate.title',
    descriptionKey: 'happiness.plans.library.workDelegate.body',
    effort: 'low',
    relatedPath: '/happiness/work',
    supportType: 'work_fulfillment',
    version: v,
  },
  {
    key: 'work-try-contribute',
    domains: ['work_fulfillment', 'meaning_purpose'],
    causeGroups: ['work', 'purpose'],
    type: 'contribution',
    titleKey: 'happiness.plans.library.workContribute.title',
    descriptionKey: 'happiness.plans.library.workContribute.body',
    effort: 'moderate',
    relatedPath: '/contribute',
    version: v,
  },
  {
    key: 'work-seek-jobs',
    domains: ['work_fulfillment'],
    causeGroups: ['work'],
    type: 'employment_jobs',
    titleKey: 'happiness.plans.library.workJobs.title',
    descriptionKey: 'happiness.plans.library.workJobs.body',
    effort: 'moderate',
    relatedPath: '/market?section=jobs',
    supportType: 'market_jobs',
    version: v,
  },
  {
    key: 'work-study',
    domains: ['work_fulfillment'],
    type: 'learning',
    titleKey: 'happiness.plans.library.workStudy.title',
    descriptionKey: 'happiness.plans.library.workStudy.body',
    effort: 'moderate',
    relatedPath: '/study',
    supportType: 'learning_program',
    version: v,
  },
];

export const FULFILLMENT_SUPPORT_OPTIONS: FulfillmentSupportOption[] = [
  {
    key: 'friend-family',
    type: 'friend_family',
    titleKey: 'happiness.plans.support.friendFamily.title',
    descriptionKey: 'happiness.plans.support.friendFamily.body',
    path: null,
  },
  {
    key: 'mentor',
    type: 'mentor',
    titleKey: 'happiness.plans.support.mentor.title',
    descriptionKey: 'happiness.plans.support.mentor.body',
    path: '/contribute',
  },
  {
    key: 'professional-wellbeing',
    type: 'professional',
    titleKey: 'happiness.plans.support.professional.title',
    descriptionKey: 'happiness.plans.support.professional.body',
    path: null,
    domains: ['health_vitality', 'emotional_wellbeing'],
  },
  {
    key: 'study',
    type: 'learning_program',
    titleKey: 'happiness.plans.support.study.title',
    descriptionKey: 'happiness.plans.support.study.body',
    path: '/study',
  },
  {
    key: 'contribute-community',
    type: 'peer_community',
    titleKey: 'happiness.plans.support.contribute.title',
    descriptionKey: 'happiness.plans.support.contribute.body',
    path: '/contribute',
  },
  {
    key: 'work-fulfillment',
    type: 'work_fulfillment',
    titleKey: 'happiness.plans.support.work.title',
    descriptionKey: 'happiness.plans.support.work.body',
    path: '/happiness/work',
    domains: ['work_fulfillment'],
  },
  {
    key: 'market-jobs',
    type: 'market_jobs',
    titleKey: 'happiness.plans.support.jobs.title',
    descriptionKey: 'happiness.plans.support.jobs.body',
    path: '/market?section=jobs',
    domains: ['work_fulfillment', 'security_stability'],
  },
  {
    key: 'community-challenge',
    type: 'civizen_group',
    titleKey: 'happiness.plans.support.challenge.title',
    descriptionKey: 'happiness.plans.support.challenge.body',
    path: '/contribute/challenges',
    domains: ['environment_community', 'time_life_balance'],
  },
  {
    key: 'governance-solutions',
    type: 'civizen_group',
    titleKey: 'happiness.plans.support.governance.title',
    descriptionKey: 'happiness.plans.support.governance.body',
    path: '/governance/solutions',
    domains: ['environment_community', 'time_life_balance', 'security_stability'],
  },
];

export function interventionByKey(key: string): FulfillmentIntervention | undefined {
  return FULFILLMENT_INTERVENTIONS.find((item) => item.key === key);
}

export function supportOptionsForDomain(domain: FulfillmentIntervention['domains'][number]): FulfillmentSupportOption[] {
  const specific = FULFILLMENT_SUPPORT_OPTIONS.filter((option) => option.domains?.includes(domain));
  const general = FULFILLMENT_SUPPORT_OPTIONS.filter((option) => !option.domains);
  return [...specific, ...general].slice(0, 5);
}

export function factorLabel(factorKey: string, translate: (key: string) => string): string {
  const key = `happiness.plans.factors.${factorKey}`;
  const label = translate(key);
  return label === key ? factorKey.replace(/_/g, ' ') : label;
}

export function isCommunitySystemPath(path: string | null): boolean {
  return Boolean(path && (/\/contribute\/challenges/.test(path) || /\/governance\/solutions/.test(path)));
}
