/** Human Outcome Review English copy. Kept out of i18n.base.ts (frozen size). */

export const OUTCOME_COPY = {
  title: 'Human Outcome Review',
  subtitle: 'What changed after this action?',
  privacyHint: 'This review uses privacy-protected group insights only.',
  noCausation:
    'A later change is not proof that this action caused it. Civizen does not establish causation from before-and-after observation.',
  operationalTitle: 'What was implemented',
  humanTitle: 'Human evidence',
  interpretationTitle: 'What this might mean',
  uncertaintyTitle: 'What we cannot conclude',
  learnTitle: 'Learn from this',
  whatHappened: 'What happened',
  humanEvidence: 'Human outcome evidence',
  startReview: 'Start outcome review',
  reviewOutcome: 'Review human outcome',
  monitoring: 'Outcome being monitored',
  noBaseline: 'No qualifying baseline available',
  insufficient: 'Not enough qualifying evidence yet',
  addFollowup: 'Add follow-up evidence',
  continueMonitoring: 'Continue monitoring',
  recordFactor: 'Record a possible other explanation',
  closeReview: 'Close review',
  publishLesson: 'Publish public-safe lesson',
  linkSolution: 'Link Solution Record',
  published: 'Public-safe lesson published',
  draftOnly: 'This is not published automatically.',
  similarTitle: 'Similar problems',
  similarCaveat: 'A similar issue elsewhere does not mean the same action will work here.',
  overlapping:
    'More than one relevant action overlapped in this period. Civizen cannot attribute the observed change to either one individually.',
  composition:
    'The participating cohort differed across these periods, so comparisons should be interpreted cautiously.',
  helpfulnessCategory:
    'Member-reported helpfulness refers to this type of action, not proof that this specific Project caused the change.',
  noScore: 'There is no numeric wellbeing impact score.',
  notPenalty: 'Human outcome results do not change contributor reputation or Civizen Score.',
  interpretationHint: 'Keep this cautious. Do not claim the Project made people happier.',
  causalBlocked: 'Causal wording is not allowed. Describe what was observed, then what remains uncertain.',
  statuses: {
    awaiting_evidence: 'Awaiting evidence',
    early_signal: 'Early signal',
    improvement_observed: 'Improvement observed',
    no_clear_change: 'No clear change',
    concern_persists: 'Concern persists',
    mixed_result: 'Mixed result',
    insufficient_evidence: 'Insufficient evidence',
    needs_further_review: 'Needs further review',
  },
  strength: {
    observation: 'Observation',
    early_association: 'Early association',
    repeated_association: 'Repeated association',
    supporting_helpfulness: 'Supporting reported helpfulness',
    evaluated_evidence: 'Evaluated evidence',
  },
  direction: {
    improving: 'Improving pattern',
    stable: 'Stable pattern',
    worsening: 'Worsening pattern',
    mixed: 'Mixed',
    suppressed: 'Not enough qualifying evidence yet',
    not_comparable: 'Not comparable',
    no_baseline: 'No qualifying baseline available',
  },
  factors: {
    overlapping_intervention: 'Overlapping action',
    external_event: 'External event',
    seasonal: 'Seasonal effect',
    composition_change: 'Participating group changed',
    other_policy: 'Another policy change',
    insufficient_evidence: 'Insufficient evidence',
    other: 'Other explanation',
  },
  closed: {
    sufficient_learning: 'Sufficient learning captured',
    no_further_monitoring: 'No further monitoring planned',
    insufficient_evidence: 'Evidence remained insufficient',
    intervention_ended: 'Action ended',
    superseded: 'Superseded by another review',
  },
  timeline: {
    baseline: 'Baseline',
    launched: 'Action started',
    followup: 'Follow-up',
  },
  domains: {
    life_satisfaction: 'Life Satisfaction',
    emotional_wellbeing: 'Emotional Wellbeing',
    meaning_purpose: 'Meaning & Purpose',
    relationships_belonging: 'Relationships & Belonging',
    health_vitality: 'Health & Vitality',
    autonomy_freedom: 'Autonomy & Freedom',
    security_stability: 'Security & Stability',
    time_life_balance: 'Time & Life Balance',
    environment_community: 'Environment & Community',
    work_fulfillment: 'Work Fulfillment',
  },
} as const;

export const CAUSAL_CLAIM = /made people happier|increased Happiness|improved Happiness|this Project caused|proved that|Happiness impact|\+\d+(\.\d+)?% Happiness|effectiveness coefficient/i;
