export {
  CLASSIFICATION_FAMILY_KEYS,
  CLASSIFICATION_NODE_TYPES,
  CLASSIFICATION_RELATIONSHIP_TYPES,
  CLASSIFICATION_SEED,
  FOUNDATIONAL_AREA_SET_ID,
  PRODUCT_PILLARS_REMAIN_CONTROLLING,
  PRODUCT_PILLAR_SET_ID,
  ClassificationRegistryError,
  getClassificationCatalog,
  getCurrentSet,
  getNodeByConceptKey,
  getNodeById,
  listAliases,
  listChildren,
  listCurrentAreas,
  listCurrentProductPillarNodes,
  listDomainsForArea,
  listFalseEquivalenceViolations,
  listNodes,
  listRelationships,
  resolveDisplay,
  validateClassificationCatalog,
  withCatalogOverlay,
} from '@/lib/classification/registry';
export type {
  ClassificationAlias,
  ClassificationCatalog,
  ClassificationDisplay,
  ClassificationNode,
  ClassificationRelationship,
  ClassificationSet,
} from '@/lib/classification/types';
