import { CLASSIFICATION_FAMILY_KEYS, type ClassificationCatalog } from '@/lib/classification/types';

const AREA_SET_ID = 'foundational_areas.v1';
const PILLAR_SET_ID = 'product_pillars.v1';

/**
 * Canonical V1 seed. Must stay aligned with
 * supabase/migrations/20260813000000_shared_classification_registry.sql
 *
 * Existing product `PILLARS` in src/lib/constants.ts remain controlling for UI.
 */
export const CLASSIFICATION_SEED: ClassificationCatalog = {
  sets: [
    {
      id: AREA_SET_ID,
      familyKey: CLASSIFICATION_FAMILY_KEYS.foundationalAreas,
      versionKey: 'v1',
      name: 'Current Foundational Area Model v1',
      description:
        'Civizen current foundational Area model originating from Mature Humanity: Health, Education, Culture, Responsibility, Environment. Evolvable; not permanently frozen.',
      status: 'current',
      isCurrent: true,
      effectiveFrom: '2026-08-13T00:00:00Z',
      effectiveTo: null,
      predecessorId: null,
      successorId: null,
      methodologyDocRef: 'docs/institutional/areas-domains-participation-framework.md',
      changeRationale: 'Seed current Area model as a versioned classification set.',
    },
    {
      id: PILLAR_SET_ID,
      familyKey: CLASSIFICATION_FAMILY_KEYS.productPillars,
      versionKey: 'v1',
      name: 'Live product PILLARS v1',
      description:
        'Current live product pillar identifiers from src/lib/constants.ts. Controlling for existing UI until a deliberate migration. Distinct from the foundational Area model.',
      status: 'current',
      isCurrent: true,
      effectiveFrom: '2026-08-13T00:00:00Z',
      effectiveTo: null,
      predecessorId: null,
      successorId: null,
      methodologyDocRef: 'src/lib/constants.ts',
      changeRationale:
        'Mirror live PILLARS as a classification set without replacing the product constant.',
    },
  ],
  nodes: [
    {
      id: `${AREA_SET_ID}.health`,
      setId: AREA_SET_ID,
      conceptKey: 'area.health',
      nodeType: 'area',
      code: 'health',
      displayName: 'Health',
      shortName: 'Health',
      description: 'Broad sphere of human health and wellbeing.',
      status: 'current',
      sortOrder: 1,
      replacedByNodeId: null,
    },
    {
      id: `${AREA_SET_ID}.education`,
      setId: AREA_SET_ID,
      conceptKey: 'area.education',
      nodeType: 'area',
      code: 'education',
      displayName: 'Education',
      shortName: 'Education',
      description: 'Broad sphere of learning and knowledge.',
      status: 'current',
      sortOrder: 2,
      replacedByNodeId: null,
    },
    {
      id: `${AREA_SET_ID}.culture`,
      setId: AREA_SET_ID,
      conceptKey: 'area.culture',
      nodeType: 'area',
      code: 'culture',
      displayName: 'Culture',
      shortName: 'Culture',
      description: 'Broad sphere of culture, values, and shared meaning.',
      status: 'current',
      sortOrder: 3,
      replacedByNodeId: null,
    },
    {
      id: `${AREA_SET_ID}.responsibility`,
      setId: AREA_SET_ID,
      conceptKey: 'area.responsibility',
      nodeType: 'area',
      code: 'responsibility',
      displayName: 'Responsibility',
      shortName: 'Responsibility',
      description:
        'Broad sphere of responsibility, including governance where displayed as Responsibility & Governance.',
      status: 'current',
      sortOrder: 4,
      replacedByNodeId: null,
    },
    {
      id: `${AREA_SET_ID}.environment`,
      setId: AREA_SET_ID,
      conceptKey: 'area.environment',
      nodeType: 'area',
      code: 'environment',
      displayName: 'Environment',
      shortName: 'Environment',
      description: 'Broad sphere of the living world and environmental stewardship.',
      status: 'current',
      sortOrder: 5,
      replacedByNodeId: null,
    },
    {
      id: `${PILLAR_SET_ID}.education_skills`,
      setId: PILLAR_SET_ID,
      conceptKey: 'pillar.education_skills',
      nodeType: 'pillar',
      code: 'education_skills',
      displayName: 'Education & Skills',
      shortName: 'Education',
      description: 'Knowledge, learning, and professional competencies',
      status: 'current',
      sortOrder: 1,
      replacedByNodeId: null,
    },
    {
      id: `${PILLAR_SET_ID}.culture_ethics`,
      setId: PILLAR_SET_ID,
      conceptKey: 'pillar.culture_ethics',
      nodeType: 'pillar',
      code: 'culture_ethics',
      displayName: 'Culture & Ethics',
      shortName: 'Culture',
      description: 'Values, integrity, and ethical behavior',
      status: 'current',
      sortOrder: 2,
      replacedByNodeId: null,
    },
    {
      id: `${PILLAR_SET_ID}.responsibility_reliability`,
      setId: PILLAR_SET_ID,
      conceptKey: 'pillar.responsibility_reliability',
      nodeType: 'pillar',
      code: 'responsibility_reliability',
      displayName: 'Responsibility & Reliability',
      shortName: 'Responsibility',
      description: 'Dependability, accountability, and follow-through',
      status: 'current',
      sortOrder: 3,
      replacedByNodeId: null,
    },
    {
      id: `${PILLAR_SET_ID}.environment_community`,
      setId: PILLAR_SET_ID,
      conceptKey: 'pillar.environment_community',
      nodeType: 'pillar',
      code: 'environment_community',
      displayName: 'Environment & Community',
      shortName: 'Community',
      description: 'Social impact and community engagement',
      status: 'current',
      sortOrder: 4,
      replacedByNodeId: null,
    },
    {
      id: `${PILLAR_SET_ID}.economy_contribution`,
      setId: PILLAR_SET_ID,
      conceptKey: 'pillar.economy_contribution',
      nodeType: 'pillar',
      code: 'economy_contribution',
      displayName: 'Economy & Contribution',
      shortName: 'Economy',
      description: 'Economic value and professional contribution',
      status: 'current',
      sortOrder: 5,
      replacedByNodeId: null,
    },
  ],
  aliases: [
    {
      id: 'alias.responsibility.en.display',
      nodeId: `${AREA_SET_ID}.responsibility`,
      alias: 'Responsibility & Governance',
      locale: 'en',
      kind: 'display',
    },
  ],
  relationships: [],
};

export const FOUNDATIONAL_AREA_SET_ID = AREA_SET_ID;
export const PRODUCT_PILLAR_SET_ID = PILLAR_SET_ID;
