"""Additional domain subsystems appended by the inventory generator."""

# Each entry: (code, items) where items match generator block() tuple shape
# (name, purpose, clas, decision, m5, m10, m20, fw, ex)

EXPANSIONS: dict[str, list] = {
    "D-HEA": [
        ("Referral care pathway engine", "Referral routing patterns", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Discharge transition of care", "Discharge planning interop", "domain-specific", "standards", 1, 3, 5, "framework-only", {}),
        ("Allergies intolerance registry", "Allergy records", "domain-specific", "standards", 2, 4, 5, "framework-only", {"data": "phi"}),
        ("Advance directives registry", "Advance care directives", "domain-specific", "reference", 1, 3, 5, "absent", {"data": "phi"}),
        ("Clinical trial registry bridge", "Trials registries", "integration", "integrate", 1, 3, 4, "absent", {}),
        ("Rare disease registries bridge", "Rare disease", "integration", "integrate", 1, 3, 4, "absent", {}),
        ("Occupational health surveillance", "Workplace health", "domain-specific", "standards", 1, 3, 4, "absent", {}),
        ("Infection control facility toolkit", "IPC tooling", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Blood bank inventory interop", "Blood banks", "integration", "integrate", 1, 3, 4, "absent", {}),
        ("Medical device UDI registry", "Device IDs", "domain-specific", "standards", 1, 3, 5, "framework-only", {}),
        ("Radiology PACS bridge patterns", "Imaging", "integration", "integrate", 1, 3, 5, "hidden-in-J-II", {}),
        ("Dental oral health record bridge", "Dental", "integration", "integrate", 1, 3, 4, "absent", {}),
        ("Primary care appointment booking", "Appointments", "domain-specific", "multi-impl", 2, 4, 5, "framework-only", {}),
        ("Ambulance EMS dispatch bridge", "EMS", "integration", "integrate", 1, 3, 5, "hidden-in-J-II", {}),
        ("Poison control knowledge base", "Poison control", "domain-specific", "reference", 1, 3, 4, "absent", {}),
        ("Healthcare workforce planning", "Workforce analytics", "domain-specific", "reference", 1, 3, 5, "framework-only", {}),
        ("Health equity disparity metrics", "Equity metrics", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Antimicrobial stewardship", "AMS programs", "domain-specific", "standards", 1, 3, 5, "framework-only", {}),
    ],
    "D-ECO": [
        ("Wage hour compliance toolkit", "Wage/hour", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Collective bargaining notice board", "Labor notices", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
        ("OSH incident reporting", "Occupational safety", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Accounting chart standards pack", "Chart of accounts patterns", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Invoice e-invoicing interop", "E-invoicing", "integration", "standards", 2, 4, 6, "partial", {}),
        ("Supply chain ESG disclosure", "ESG supply", "domain-specific", "standards", 1, 3, 5, "framework-only", {}),
        ("Franchise licensing cases", "Franchises", "domain-specific", "reference", 1, 3, 4, "absent", {}),
        ("Export import license cases", "Trade licenses", "domain-specific", "reference", 1, 3, 5, "framework-only", {}),
        ("Price transparency publication", "Price pubs", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
        ("Sectoral collective agreement registry", "Sector agreements", "domain-specific", "integrate", 1, 3, 4, "absent", {}),
        ("Unemployment insurance bridge", "UI systems", "integration", "integrate", 1, 3, 5, "hidden-in-J-II", {}),
        ("Workplace inspection scheduling", "Inspections", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
        ("Economic development grant admin", "Dev grants", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Antitrust merger notification", "Merger notice", "domain-specific", "leave-to-J", 0, 2, 4, "absent", {}),
        ("Consumer credit installment rules aid", "Installment aid", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
    ],
    "D-FIN": [
        ("Deposit insurance notice bridge", "Deposit insurance", "integration", "leave-to-J", 0, 2, 4, "absent", {}),
        ("Central bank reporting adapter", "Reporting only", "integration", "integrate", 1, 3, 4, "absent", {}),
        ("FX settlement messaging bridge", "FX messaging", "integration", "integrate", 1, 3, 4, "absent", {}),
        ("Trade finance document toolkit", "Trade finance", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
        ("Pension fund disclosure portal", "Pension disclosure", "domain-specific", "standards", 1, 3, 5, "framework-only", {}),
        ("Microfinance cooperative ledger", "Microfinance", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Card scheme certification checklist", "Card compliance", "domain-specific", "standards", 2, 3, 5, "framework-only", {}),
        ("Financial consumer complaint routing", "Fin complaints", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Systemic risk indicator feed", "Non-authoritative", "domain-specific", "standards", 0, 2, 4, "absent", {}),
        ("Islamic finance product labels", "Where relevant", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
    ],
    "D-TAX": [
        ("VAT GST invoice matching", "VAT matching", "integration", "integrate", 1, 3, 5, "hidden-in-J-II", {}),
        ("Tax treaty relief claim aid", "Treaty relief", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
        ("Excise stamp tracking", "Excise", "domain-specific", "integrate", 1, 3, 4, "absent", {}),
        ("Fiscal transparency open data", "Open fiscal data", "domain-specific", "operate", 3, 5, 6, "partial", {}),
        ("Debt management publication", "Public debt pubs", "domain-specific", "standards", 1, 3, 5, "framework-only", {}),
        ("Transfer pricing documentation aid", "TP docs", "domain-specific", "standards", 1, 3, 4, "absent", {}),
        ("Tax dispute case docket", "Tax disputes", "domain-specific", "leave-to-J", 1, 3, 4, "absent", {}),
        ("Municipal fee collection bridge", "Local fees", "integration", "integrate", 2, 4, 5, "hidden-in-J-II", {}),
    ],
    "D-EDU": [
        ("K12 enrollment transfer system", "Enrollment", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Special education IEP cases", "Special education", "domain-specific", "reference", 1, 3, 5, "framework-only", {"data": "education_sensitive"}),
        ("Teacher licensing registry", "Teachers", "domain-specific", "integrate", 2, 4, 5, "hidden-in-J-II", {}),
        ("Curriculum standards publication", "Curricula", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Library catalog interop", "Libraries", "integration", "standards", 2, 4, 5, "framework-only", {}),
        ("Open educational resources hub", "OER", "domain-specific", "operate", 3, 5, 6, "partial", {}),
        ("Research data management plans", "DMP tooling", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Early childhood program registry", "ECE", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Adult literacy program cases", "Adult literacy", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Exam integrity proctoring limits", "Exam integrity — privacy constraints", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
    ],
    "D-SCI": [
        ("Instrument facility booking", "Shared instruments", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
        ("Specimen biobank consent", "Biobanks", "domain-specific", "reference", 1, 3, 4, "absent", {"data": "bio"}),
        ("Open science reproducibility toolkit", "Reproducibility", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Standards metrology registry", "Metrology", "domain-specific", "integrate", 1, 3, 5, "framework-only", {}),
        ("Citizen science project platform", "Citizen science", "domain-specific", "multi-impl", 2, 4, 5, "framework-only", {}),
        ("Technology transfer case admin", "Tech transfer", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
    ],
    "D-HOU": [
        ("Rental tenancy dispute mediation", "Tenancy", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Eviction moratorium notice board", "Notices", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
        ("Construction code compliance cases", "Building codes", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Informal settlement upgrading", "Upgrading programs", "domain-specific", "reference", 1, 3, 5, "framework-only", {}),
        ("Property valuation appeal", "Valuation appeals", "domain-specific", "leave-to-J", 1, 3, 4, "absent", {}),
        ("Communal land rights interface", "Communal rights — never centralize", "domain-specific", "standards", 1, 3, 5, "framework-only", {"never_c": "true"}),
        ("Smart city IoT privacy gateway", "IoT privacy", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
        ("Affordable housing lottery", "Allocation lotteries", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
    ],
    "D-FOO": [
        ("Irrigation water rights ledger", "Water rights", "domain-specific", "leave-to-J", 1, 3, 4, "absent", {}),
        ("Fisheries quota registry", "Fisheries", "domain-specific", "integrate", 1, 3, 4, "absent", {}),
        ("Pesticide approval registry", "Pesticides", "domain-specific", "integrate", 1, 3, 4, "absent", {}),
        ("Seed variety registry", "Seeds", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
        ("School feeding program admin", "School meals", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Nutrition labeling compliance", "Labels", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Drought early action protocols", "Drought protocols", "domain-specific", "reference", 1, 3, 5, "framework-only", {}),
        ("Sanitation utility bridge", "Sanitation", "integration", "integrate", 1, 3, 5, "hidden-in-J-II", {}),
    ],
    "D-ENE": [
        ("Grid interconnection queue", "Interconnection", "domain-specific", "leave-to-J", 1, 3, 4, "absent", {}),
        ("Fuel quality inspection", "Fuels", "domain-specific", "integrate", 1, 3, 4, "absent", {}),
        ("Nuclear materials accounting", "Nuclear — J/IAEA class only", "domain-specific", "prohibit-global-central", 0, 1, 2, "absent", {"never_c": "true"}),
        ("Energy poverty subsidy intake", "Energy poverty", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Critical minerals trade transparency", "Minerals", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
        ("Just transition workforce map", "Transition jobs", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
    ],
    "D-TRA": [
        ("Driver license credential verify", "DL verify", "integration", "integrate", 2, 4, 5, "hidden-in-J-II", {}),
        ("Aviation safety occurrence report", "Aviation", "domain-specific", "integrate", 1, 3, 4, "absent", {}),
        ("Maritime port community system", "Ports", "integration", "integrate", 1, 3, 4, "absent", {}),
        ("Bike micromobility share data", "Micromobility", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Accessible parking permit registry", "Accessible parking", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Customs transit guarantee", "Transit guarantees", "integration", "integrate", 1, 3, 4, "absent", {}),
        ("Urban congestion pricing bridge", "Congestion", "integration", "leave-to-J", 1, 3, 4, "absent", {}),
        ("School bus routing privacy", "School transport", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
    ],
    "D-COM": [
        ("Universal service fund admin", "USF", "domain-specific", "leave-to-J", 1, 3, 4, "absent", {}),
        ("Net neutrality complaint routing", "NN complaints", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
        ("Emergency number location privacy", "E911-class privacy", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Postal address modernization", "Addresses", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Content moderation transparency", "Platform transparency", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Community radio licensing aid", "Community radio", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
    ],
    "D-ENV": [
        ("EIA case management", "Environmental impact", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Air quality index publication", "AQI", "domain-specific", "operate", 3, 5, 6, "partial", {}),
        ("Water quality monitoring exchange", "Water quality", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Hazardous waste shipment tracking", "Hazwaste", "domain-specific", "integrate", 1, 3, 5, "framework-only", {}),
        ("Circular economy material passport", "Material passports", "domain-specific", "standards", 1, 3, 5, "framework-only", {}),
        ("Nature-based solution registry", "NbS projects", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Invasive species early detection", "Invasives", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
        ("Noise pollution complaint system", "Noise", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
    ],
    "D-SOC": [
        ("Cash transfer payment orchestration", "Cash transfers", "domain-specific", "reference", 2, 4, 6, "partial", {}),
        ("Means test evidence locker", "Means-test evidence", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Elder abuse reporting pathway", "Elder abuse", "domain-specific", "reference", 2, 4, 5, "framework-only", {"data": "highly_sensitive"}),
        ("Foster care case bridge", "Foster care — J", "integration", "leave-to-J", 1, 3, 4, "absent", {"data": "highly_sensitive"}),
        ("Adoption registry bridge", "Adoption — J", "integration", "leave-to-J", 0, 2, 4, "absent", {}),
        ("Disability assistive tech voucher", "AT vouchers", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Long-term care facility registry", "LTC facilities", "domain-specific", "integrate", 1, 3, 5, "hidden-in-J-II", {}),
        ("Family leave benefits bridge", "Family leave", "integration", "integrate", 1, 3, 5, "hidden-in-J-II", {}),
        ("Social service case continuity", "Case continuity", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
    ],
    "D-JUS": [
        ("Bail bond conditions registry", "Bail — J", "domain-specific", "leave-to-J", 0, 2, 3, "absent", {}),
        ("Public defender assignment", "Defense counsel", "domain-specific", "reference", 1, 3, 5, "framework-only", {}),
        ("Jury management bridge", "Juries", "integration", "leave-to-J", 0, 2, 3, "absent", {}),
        ("Forensic lab evidence custody", "Forensics — J", "domain-specific", "leave-to-J", 0, 2, 3, "absent", {}),
        ("Prisoner rehabilitation programs", "Rehab programs", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
        ("Juvenile justice privacy vault", "Juvenile — heightened", "domain-specific", "leave-to-J", 0, 2, 4, "absent", {"data": "highly_sensitive", "never_c": "true"}),
        ("Civil small claims e-filing", "Small claims", "domain-specific", "multi-impl", 2, 4, 5, "framework-only", {}),
        ("Warrant service privacy limits", "Warrants — no global DB", "domain-specific", "prohibit-global-central", 0, 1, 2, "absent", {"never_c": "true"}),
        ("Fire EMS mutual aid agreements", "Mutual aid", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
    ],
    "D-RGT": [
        ("Equality impact assessment toolkit", "EqIA", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Hate crime reporting pathway", "Hate crime reports", "domain-specific", "reference", 1, 3, 5, "framework-only", {}),
        ("Privacy rights request portal", "DSAR-class", "domain-specific", "operate", 3, 5, 6, "partial", {}),
        ("Freedom of assembly permit aid", "Assembly permits", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
        ("Indigenous rights FPIC workflow", "FPIC", "domain-specific", "standards", 2, 4, 5, "framework-only", {"never_c": "true"}),
        ("Child rights monitoring indicators", "Child rights", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Detention monitoring visit logs", "Detention monitors", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
    ],
    "D-MIG": [
        ("Work permit sponsorship cases", "Work permits", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Family reunification case aid", "Family reunification", "domain-specific", "reference", 1, 3, 5, "framework-only", {}),
        ("Naturalization civic education", "Civic education", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Temporary protection status", "TPS-class", "domain-specific", "leave-to-J", 1, 3, 4, "framework-only", {}),
        ("Remittance identity friction reduce", "Remittance KYC friction", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Lost passport emergency aid", "Emergency docs", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Immigration detention visitation", "Detention visits", "domain-specific", "leave-to-J", 0, 2, 4, "absent", {}),
    ],
    "D-EMR": [
        ("Multi-hazard risk atlas", "Risk atlas", "domain-specific", "operate", 2, 4, 5, "framework-only", {}),
        ("Search rescue volunteer roster", "SAR volunteers", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Dead body identification privacy", "DVI privacy", "domain-specific", "standards", 1, 3, 4, "absent", {"data": "highly_sensitive"}),
        ("Cash voucher assistance delivery", "CVA", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Epidemic surge bed capacity", "Surge capacity", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Cross-border relief corridor", "Relief corridors", "domain-specific", "standards", 1, 3, 5, "framework-only", {}),
        ("Business continuity mutual aid", "BCP mutual aid", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
    ],
    "D-CUL": [
        ("Museum collection catalog interop", "Museums", "integration", "standards", 1, 3, 5, "framework-only", {}),
        ("Endangered language archive", "Language archives", "domain-specific", "operate", 2, 4, 6, "partial", {}),
        ("Press freedom incident monitor", "Press freedom", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
        ("Cultural property restitution cases", "Restitution", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
        ("Public library digital lending", "E-lending", "domain-specific", "multi-impl", 2, 4, 5, "framework-only", {}),
        ("Festival permit case system", "Festivals", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
    ],
    "D-IND": [
        ("Professional board licensing", "Boards", "domain-specific", "integrate", 2, 4, 5, "hidden-in-J-II", {}),
        ("Hazardous facility permitting", "Haz facilities", "domain-specific", "reference", 1, 3, 5, "framework-only", {}),
        ("Metrology weights measures", "Weights/measures", "domain-specific", "integrate", 1, 3, 5, "framework-only", {}),
        ("Import product safety holds", "Import holds", "domain-specific", "integrate", 1, 3, 5, "framework-only", {}),
        ("Cooperative formation wizard", "Coop formation", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Sandbox regulatory experiment", "Reg sandboxes", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
    ],
    "D-CON": [
        ("Warranty claim routing", "Warranties", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Dark pattern complaint taxonomy", "Dark patterns", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Toy product safety registry", "Toys", "domain-specific", "integrate", 1, 3, 5, "framework-only", {}),
        ("Food allergen labeling enforce", "Allergen labels", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Online marketplace seller trust", "Seller trust", "domain-specific", "multi-impl", 2, 4, 5, "framework-only", {}),
        ("Class action notice publication", "Class notices", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
    ],
    "D-DEF": [
        ("Civilian casualty reporting civil", "Civil reporting", "domain-specific", "standards", 0, 2, 3, "absent", {}),
        ("Demining clearance registry", "Demining", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
        ("Veterans benefits bridge", "Veterans", "integration", "integrate", 1, 3, 5, "hidden-in-J-II", {}),
        ("Cyber defense coordination civil", "Civil cyber only", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Conflict early warning open source", "Open-source early warning", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
    ],
    "D-INT": [
        ("Treaty ratification tracker", "Treaties — non-authoritative", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
        ("Consular assistance case aid", "Consular", "domain-specific", "reference", 1, 3, 4, "framework-only", {}),
        ("International organization roster", "IO roster", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Cross-border data transfer catalogs", "Transfer catalogs", "domain-specific", "standards", 2, 4, 6, "partial", {}),
        ("Extradition case interface limits", "Extradition — J only", "domain-specific", "prohibit-global-central", 0, 1, 2, "absent", {"never_c": "true"}),
    ],
    "D-ELE": [
        ("Petition initiative signature verify", "Petitions", "domain-specific", "multi-impl", 2, 4, 5, "framework-only", {}),
        ("Legislative bill drafting aid", "Bill drafting", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Committee hearing publication", "Hearings", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Lobbying disclosure registry", "Lobbying", "domain-specific", "reference", 1, 3, 5, "framework-only", {}),
        ("Public procurement integrity red flags", "Procurement red flags", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Civil service ethics disclosure", "Ethics disclosures", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Referendum question clarity aid", "Referendum clarity", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
        ("Election results publication verify", "Results pubs — J authority", "domain-specific", "integrate", 1, 3, 5, "hidden-in-J-II", {"never_c": "true"}),
    ],
    "D-CSO": [
        ("Mutual aid resource map", "Mutual aid", "domain-specific", "operate", 3, 5, 6, "partial", {}),
        ("Nonprofit financial transparency", "Nonprofit finance", "domain-specific", "standards", 2, 4, 5, "framework-only", {}),
        ("Community land trust registry", "CLTs", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Youth council participation toolkit", "Youth councils", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Neighborhood association portal", "Neighborhoods", "domain-specific", "multi-impl", 2, 4, 5, "framework-only", {}),
        ("Faith-based social service bridge", "Faith social services", "domain-specific", "standards", 1, 3, 4, "framework-only", {}),
    ],
    "D-MEA": [
        ("National accounts bridge", "SNA-class", "integration", "integrate", 1, 3, 5, "absent", {}),
        ("Geospatial base map commons", "Base maps", "domain-specific", "multi-impl", 3, 5, 6, "partial", {}),
        ("Administrative boundary service", "Boundaries", "domain-specific", "standards", 2, 4, 6, "partial", {}),
        ("Price index collection toolkit", "Price indices", "domain-specific", "standards", 1, 3, 5, "framework-only", {}),
        ("Impact evaluation registry", "Evaluations", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Misinformation claim evidence locker", "Evidence lockers", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Open government data portal kit", "OGD portals", "domain-specific", "reference", 3, 5, 6, "partial", {}),
    ],
    "D-ADD": [
        ("Community kitchen coordination", "Community kitchens", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Public park amenity booking", "Parks", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Maker space equipment share", "Makerspaces", "domain-specific", "reference", 2, 4, 5, "framework-only", {}),
        ("Timebank reciprocal exchange", "Timebanks", "domain-specific", "multi-impl", 1, 3, 5, "framework-only", {}),
        ("Orbital debris reporting feed", "Debris reporting", "domain-specific", "standards", 0, 2, 3, "absent", {}),
        ("Undersea cable landing permits", "Cable landings", "domain-specific", "leave-to-J", 0, 2, 3, "absent", {}),
        ("Commons license template library", "Commons licenses", "domain-specific", "operate", 3, 5, 6, "partial", {}),
        ("Intergenerational care matching", "Care matching", "domain-specific", "reference", 1, 3, 5, "framework-only", {}),
    ],
}

# Extra horizontal / cross-cutting systems not in the 91
HORIZONTAL_EXTRA = [
    ("H-X-001", "Shared notification delivery fabric", "Multi-channel notifications reused across systems", "horizontal.apis_standards_interop", "global", "shared-core", "operate", 4, 6, 7, "adequate", {"map11": "core-platform", "never_c": "false"}),
    ("H-X-002", "Shared case pattern engine", "Generic case workflows", "horizontal.public_services_case", "global", "shared-core", "operate", 4, 6, 7, "adequate", {"map11": "core-platform"}),
    ("H-X-003", "Shared evidence locker", "Tamper-evident evidence storage patterns", "horizontal.legislation_records", "global", "shared-core", "reference", 3, 5, 7, "partial", {"map11": "core-platform"}),
    ("H-X-004", "Shared consent ledger", "Cross-domain consent", "horizontal.privacy_data", "global", "shared-core", "operate", 4, 6, 7, "adequate", {"map11": "core-platform"}),
    ("H-X-005", "Shared rate-limit abuse fabric", "Abuse controls", "horizontal.security_resilience", "global", "shared-core", "operate", 4, 6, 7, "adequate", {"map11": "assurance"}),
    ("H-X-006", "Operator certification exam system", "Certify operators", "horizontal.deployment_federation_ops", "global", "shared-core", "operate", 3, 5, 6, "partial", {"map11": "operator-network.establishment"}),
    ("H-X-007", "Federation partition playbooks", "Geopolitical partition drills", "horizontal.deployment_federation_ops", "global", "shared-core", "reference", 2, 4, 6, "partial", {"map11": "reserves"}),
    ("H-X-008", "Cryptographic algorithm agility", "Crypto migration program", "horizontal.security_resilience", "global", "shared-core", "operate", 2, 4, 7, "partial", {"map11": "reserves"}),
    ("H-X-009", "Archival century retention vault", "Long-horizon archives", "horizontal.legislation_records", "global", "shared-core", "federate", 2, 4, 6, "partial", {"map11": "core-platform"}),
    ("H-X-010", "Nondigital service channel kit", "Paper/phone/kiosk patterns", "horizontal.accessibility_localization", "jurisdictional", "shared-core", "reference", 3, 5, 7, "partial", {"map11": "accessibility-localization"}),
    ("H-X-011", "Low-connectivity sync protocol", "Offline-first sync", "horizontal.apis_standards_interop", "global", "shared-core", "operate", 3, 5, 7, "partial", {"map11": "core-platform"}),
    ("H-X-012", "Institutional onboarding factory", "Repeatable institution onboarding", "horizontal.adoption_education_support", "global", "shared-core", "operate", 3, 5, 6, "partial", {"map11": "adoption-education-support"}),
    ("H-X-013", "Independent assurance evidence portal", "Assurance evidence", "horizontal.audit_fraud_appeals", "global", "shared-core", "reference", 3, 5, 6, "partial", {"map11": "independent-governance"}),
    ("H-X-014", "Multi-party escrow continuity vault", "Funding continuity escrow", "horizontal.payments_accounting", "global", "shared-core", "federate", 2, 4, 5, "partial", {"map11": "reserves"}),
    ("H-X-015", "Shared terminology translation memory", "Domain term L10n memory", "horizontal.accessibility_localization", "global", "shared-core", "operate", 3, 5, 7, "partial", {"map11": "accessibility-localization"}),
]
