/** Wellbeing Insights English copy. Kept out of i18n.base.ts (frozen size). */

export const INSIGHTS_COPY = {
  title: 'Wellbeing Insights',
  privacyHint: 'These are privacy-protected group insights.',
  howTitle: 'How this works',
  howBody: [
    'Individual Happiness & Fulfillment records remain private.',
    'Only qualifying group-level information is shown.',
    'Small or overly specific groups are suppressed.',
    'Participation is optional.',
    'These insights are intended to improve conditions, not evaluate individuals.',
  ],
  coordinatorLimits:
    'Do not use this to identify individuals, rank teams, evaluate managers, or infer who is seeking other work.',
  overview: 'Overview',
  patterns: 'Patterns',
  action: 'Action',
  goingWell: 'Going well',
  needsAttention: 'Needs attention',
  emerging: 'Emerging patterns',
  established: 'Established patterns',
  monitoring: 'Monitoring',
  recentMovement: 'Recent movement',
  whatShouldIKnow: 'What should I know right now?',
  suppressedTitle: 'Not enough qualifying information yet',
  suppressedBody:
    'This insight is unavailable because the privacy requirements for this group are not currently met.',
  emptyTitle: 'No qualifying group insight yet',
  emptyBody: 'Privacy requirements have not yet been met for this scope and period.',
  scopeDisabledTitle: 'Group insights are not enabled',
  scopeDisabledBody: 'This group has not enabled privacy-protected wellbeing insights.',
  unauthorizedTitle: 'This wellbeing insight is not available.',
  unauthorizedBody: 'You can view insights only for an approved group you are authorized to see.',
  noViewerTitle: 'No authorized group yet',
  noViewerBody: 'Wellbeing Insights appears when you are an authorized viewer for an approved organization or community.',
  sufficiency: { insufficient: 'Insufficient', sufficient: 'Sufficient', broad: 'Broad' },
  trend: { improving: 'Improving', stable: 'Stable', declining: 'Declining', unknown: 'Not enough to describe a trend' },
  polarity: { going_well: 'Going well', needs_attention: 'Needs attention', mixed: 'Mixed' },
  problem: {
    individual_support: 'This pattern may reflect a personal-support need.',
    institutional_condition: 'This pattern may reflect an institutional condition.',
    community_system: 'This pattern may reflect a community or system condition.',
    unclear: 'There is not enough qualifying evidence to classify this pattern.',
  },
  noCausation: 'These factors appear repeatedly in qualifying aggregate periods. They do not establish causation.',
  helpfulnessCaveat: 'These are member-reported outcomes, not proof that the action caused the change.',
  whatMightHelp: 'What participating members have reported as helpful',
  associatedFactors: 'Frequently associated factors',
  investigate: 'Investigate further',
  continueMonitoring: 'Continue monitoring',
  viewExisting: 'View existing effort',
  contributeEvidence: 'Contribute evidence',
  exploreChallenge: 'Explore as Community Challenge',
  exploreGovernance: 'Explore in Governance Solutions',
  relatedEffort: 'Related existing effort',
  evidenceNote: 'Evidence is a privacy-protected group insight. It does not identify members.',
  draftOnly: 'This opens a draft. Nothing is published automatically.',
  noParticipants: 'Who participated is not shown.',
  timeQuarter: 'Quarter',
  timeMonth: 'Month',
  timeRolling: 'Rolling six weeks',
  askCivi: 'Ask Civi about this pattern',
  reviewPatterns: 'Review emerging patterns',
  domains: {
    life_satisfaction: 'Life Satisfaction',
    emotional_wellbeing: 'Emotional Wellbeing',
    meaning_purpose: 'Meaning & Purpose',
    relationships_belonging: 'Relationships & Belonging',
    health_vitality: 'Health & Vitality',
    autonomy_freedom: 'Autonomy & Freedom',
    security_stability: 'Security & Stability',
    time_life_balance: 'Time & Life Balance',
    environment_community: 'Environment & Community',
    work_fulfillment: 'Work Fulfillment',
  },
} as const;
